<a href="https://colab.research.google.com/github/ManuelRomero2025/Programaci-nPython20254/blob/main/Clasefull_300820252.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Escalar: un número**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#escalar
a=10.
b=8
c=-10


In [ ]:
np.ndim(a)

0

In [ ]:
x=a+b
print(x)

18.0


**Matriz**

In [ ]:
import numpy as np
#vector
Vector=np.array([12,12. ,24,25.,26,14,14,15.,16])
print(Vector)

[12. 12. 24. 25. 26. 14. 14. 15. 16.]


In [ ]:
np.shape(Vector)

(9,)

In [ ]:
np.ndim(Vector)

1

In [ ]:
#matriz
Matriz=np.array([[10,12,13],[24,25,26],[37,38,0]])
print(Matriz)

[[10 12 13]
 [24 25 26]
 [37 38  0]]


In [ ]:
np.shape(Matriz)

(3, 3)

In [ ]:
# Dimensión
np.ndim(Matriz)

2

In [ ]:
Matriz1=np.array([[[12,13,15],[22,23,24]],
                   [[33,34,35],[36,37,38]],
                 [[42,43,44],[45,46,47]]])
print(Matriz1)

[[[12 13 15]
  [22 23 24]]

 [[33 34 35]
  [36 37 38]]

 [[42 43 44]
  [45 46 47]]]


In [ ]:
np.shape(Matriz1)

(3, 2, 3)

In [ ]:
np.ndim(Matriz1)

3

In [ ]:
Matriz1[0]

array([[12, 13, 15],
       [22, 23, 24]])

In [ ]:
Matriz1[1]

array([[33, 34, 35],
       [36, 37, 38]])

In [ ]:
Matriz1[2]

array([45, 46, 47])

In [ ]:
Matriz1[0][0]

array([12, 13, 15])

In [ ]:
Matriz1[0][0][0]

np.int64(12)

**Operaciones**

In [ ]:
Vector*0.5

array([ 6. ,  6. , 12. , 12.5, 13. ,  7. ,  7. ,  7.5,  8. ])

In [ ]:
Vector+10

array([22., 22., 34., 35., 36., 24., 24., 25., 26.])

In [ ]:
Vector-5

array([ 7.,  7., 19., 20., 21.,  9.,  9., 10., 11.])

In [ ]:
Vector/10

array([1.2, 1.2, 2.4, 2.5, 2.6, 1.4, 1.4, 1.5, 1.6])

In [ ]:
Matriz

array([[10, 12, 13],
       [24, 25, 26],
       [37, 38,  0]])

In [ ]:
Matriz*2

array([[20, 24, 26],
       [48, 50, 52],
       [74, 76,  0]])

In [ ]:
Matriz-20

array([[-10,  -8,  -7],
       [  4,   5,   6],
       [ 17,  18, -20]])

In [ ]:
Matriz/10

array([[1. , 1.2, 1.3],
       [2.4, 2.5, 2.6],
       [3.7, 3.8, 0. ]])

In [ ]:
Matriz1

array([[[12, 13, 15],
        [22, 23, 24]],

       [[33, 34, 35],
        [36, 37, 38]],

       [[42, 43, 44],
        [45, 46, 47]]])

In [ ]:
Matriz1*3

array([[[ 36,  39,  45],
        [ 66,  69,  72]],

       [[ 99, 102, 105],
        [108, 111, 114]],

       [[126, 129, 132],
        [135, 138, 141]]])

In [ ]:
Matriz+4

array([[14, 16, 17],
       [28, 29, 30],
       [41, 42,  4]])

In [ ]:
Matriz1/10

array([[[1.2, 1.3, 1.5],
        [2.2, 2.3, 2.4]],

       [[3.3, 3.4, 3.5],
        [3.6, 3.7, 3.8]],

       [[4.2, 4.3, 4.4],
        [4.5, 4.6, 4.7]]])

**Vectores tipo cadena**

In [ ]:
Cadena=np.array(["Hola","Mundo"])
print(Cadena)

['Hola' 'Mundo']


In [ ]:
Cadena1=np.array([["Manuel", "Bogotá"],
                  ["Ginna", "Sopó"]])
print(Cadena1)

[['Manuel' 'Bogotá']
 ['Ginna' 'Sopó']]


In [ ]:
cadena2=np.array([[["MANUEL","BOGOTÁ"],["gINNA", "SOP0"]],
                  [["Venta", "Carro"],["Venta", "Casa"]],
                  [["Arriendo", "alto"],["ESTADO","CASADO"]]])
print(cadena2)

[[['MANUEL' 'BOGOTÁ']
  ['gINNA' 'SOP0']]

 [['Venta' 'Carro']
  ['Venta' 'Casa']]

 [['Arriendo' 'alto']
  ['ESTADO' 'CASADO']]]


Otras Operaciones

In [ ]:
np.arange(21)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
np.arange(0,1.01,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [ ]:
np.arange(20,100,5)

array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [ ]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(20,50,40)

array([20.        , 20.76923077, 21.53846154, 22.30769231, 23.07692308,
       23.84615385, 24.61538462, 25.38461538, 26.15384615, 26.92307692,
       27.69230769, 28.46153846, 29.23076923, 30.        , 30.76923077,
       31.53846154, 32.30769231, 33.07692308, 33.84615385, 34.61538462,
       35.38461538, 36.15384615, 36.92307692, 37.69230769, 38.46153846,
       39.23076923, 40.        , 40.76923077, 41.53846154, 42.30769231,
       43.07692308, 43.84615385, 44.61538462, 45.38461538, 46.15384615,
       46.92307692, 47.69230769, 48.46153846, 49.23076923, 50.        ])

In [ ]:
np.ndim(np.linspace(20,50,40))

1

In [ ]:
np.shape(np.linspace(20,50,40))

(40,)

In [ ]:
Matriz3=np.array([np.arange(10,30), np.arange(20,40)])
print(Matriz3)

[[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]]


In [ ]:
Matriz4=np.arange(40).reshape(4,10)
print(Matriz4)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


In [ ]:
Matriz4=np.arange(40).reshape(8,5)
print(Matriz4)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [ ]:
Matriz5=np.linspace(0,100,20).reshape(4,5)
print(Matriz5)

[[  0.           5.26315789  10.52631579  15.78947368  21.05263158]
 [ 26.31578947  31.57894737  36.84210526  42.10526316  47.36842105]
 [ 52.63157895  57.89473684  63.15789474  68.42105263  73.68421053]
 [ 78.94736842  84.21052632  89.47368421  94.73684211 100.        ]]


In [ ]:
np.max(Matriz5)#matriz

np.float64(100.0)

In [ ]:
np.max(Matriz5, axis=0)#columna

array([ 78.94736842,  84.21052632,  89.47368421,  94.73684211,
       100.        ])

In [ ]:
np.max(Matriz5, axis=1)#fila

array([ 21.05263158,  47.36842105,  73.68421053, 100.        ])

In [ ]:
np.min(Matriz5, axis=0)#columna

array([ 0.        ,  5.26315789, 10.52631579, 15.78947368, 21.05263158])

In [ ]:
np.mean(Matriz5, axis=0)#columna

array([39.47368421, 44.73684211, 50.        , 55.26315789, 60.52631579])

In [ ]:
np.sum(Matriz5, axis=0)#columna

array([157.89473684, 178.94736842, 200.        , 221.05263158,
       242.10526316])

In [ ]:
#CANTIDAD DE COLUMNAS
len(Matriz5.T)#Transpuesta

5

In [ ]:
#CANTIDAD DE FINAL
len(Matriz5)

4

In [ ]:
print(Matriz5)

[[  0.           5.26315789  10.52631579  15.78947368  21.05263158]
 [ 26.31578947  31.57894737  36.84210526  42.10526316  47.36842105]
 [ 52.63157895  57.89473684  63.15789474  68.42105263  73.68421053]
 [ 78.94736842  84.21052632  89.47368421  94.73684211 100.        ]]


In [ ]:
print(Matriz5.T)

[[  0.          26.31578947  52.63157895  78.94736842]
 [  5.26315789  31.57894737  57.89473684  84.21052632]
 [ 10.52631579  36.84210526  63.15789474  89.47368421]
 [ 15.78947368  42.10526316  68.42105263  94.73684211]
 [ 21.05263158  47.36842105  73.68421053 100.        ]]


In [ ]:
np.hsplit(Matriz5,1)

[array([[  0.        ,   5.26315789,  10.52631579,  15.78947368,
          21.05263158],
        [ 26.31578947,  31.57894737,  36.84210526,  42.10526316,
          47.36842105],
        [ 52.63157895,  57.89473684,  63.15789474,  68.42105263,
          73.68421053],
        [ 78.94736842,  84.21052632,  89.47368421,  94.73684211,
         100.        ]])]

In [ ]:
np.vsplit(Matriz5,1)

[array([[  0.        ,   5.26315789,  10.52631579,  15.78947368,
          21.05263158],
        [ 26.31578947,  31.57894737,  36.84210526,  42.10526316,
          47.36842105],
        [ 52.63157895,  57.89473684,  63.15789474,  68.42105263,
          73.68421053],
        [ 78.94736842,  84.21052632,  89.47368421,  94.73684211,
         100.        ]])]

In [ ]:
Vector=np.hsplit(Matriz5,5)
print(Vector)

[array([[ 0.        ],
       [26.31578947],
       [52.63157895],
       [78.94736842]]), array([[ 5.26315789],
       [31.57894737],
       [57.89473684],
       [84.21052632]]), array([[10.52631579],
       [36.84210526],
       [63.15789474],
       [89.47368421]]), array([[15.78947368],
       [42.10526316],
       [68.42105263],
       [94.73684211]]), array([[ 21.05263158],
       [ 47.36842105],
       [ 73.68421053],
       [100.        ]])]


In [ ]:
Vector[0]

array([[ 0.        ],
       [26.31578947],
       [52.63157895],
       [78.94736842]])

In [ ]:
Vector[1]

array([[ 5.26315789],
       [31.57894737],
       [57.89473684],
       [84.21052632]])

In [ ]:
Vector[2]

array([[10.52631579],
       [36.84210526],
       [63.15789474],
       [89.47368421]])

In [ ]:
np.concatenate((Vector[0],Vector[1], Vector[3]),axis=0)

array([[ 0.        ],
       [26.31578947],
       [52.63157895],
       [78.94736842],
       [ 5.26315789],
       [31.57894737],
       [57.89473684],
       [84.21052632],
       [15.78947368],
       [42.10526316],
       [68.42105263],
       [94.73684211]])

Operaciones Lógica

In [ ]:
a=10
b=20
a!=b#diferente

True

In [ ]:
a<=b# menor e igual

True

In [ ]:
a<b# menor que

True

In [ ]:
a>b #mayor que

False

In [ ]:
a>=b#mayor e igual

False

In [ ]:
a==b #alores iguales

False

In [ ]:
x1=np.linspace(20,90,50)
print(x1)

[20.         21.42857143 22.85714286 24.28571429 25.71428571 27.14285714
 28.57142857 30.         31.42857143 32.85714286 34.28571429 35.71428571
 37.14285714 38.57142857 40.         41.42857143 42.85714286 44.28571429
 45.71428571 47.14285714 48.57142857 50.         51.42857143 52.85714286
 54.28571429 55.71428571 57.14285714 58.57142857 60.         61.42857143
 62.85714286 64.28571429 65.71428571 67.14285714 68.57142857 70.
 71.42857143 72.85714286 74.28571429 75.71428571 77.14285714 78.57142857
 80.         81.42857143 82.85714286 84.28571429 85.71428571 87.14285714
 88.57142857 90.        ]


In [ ]:
x1==70

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [ ]:
x1>=60

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [ ]:
x2=np.array([np.arange(10)])
x2

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
np.where(x2==5, 1, 0)

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [ ]:
np.where(x2>=4, "Ok", "No Ok")

array([['No Ok', 'No Ok', 'No Ok', 'No Ok', 'Ok', 'Ok', 'Ok', 'Ok', 'Ok',
        'Ok']], dtype='<U5')

In [ ]:
V1=np.arange(45).reshape(3,3,5)
print(V1)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]


In [ ]:
np.where(V1>=20, "Ok", "No Ok")


array([[['No Ok', 'No Ok', 'No Ok', 'No Ok', 'No Ok'],
        ['No Ok', 'No Ok', 'No Ok', 'No Ok', 'No Ok'],
        ['No Ok', 'No Ok', 'No Ok', 'No Ok', 'No Ok']],

       [['No Ok', 'No Ok', 'No Ok', 'No Ok', 'No Ok'],
        ['Ok', 'Ok', 'Ok', 'Ok', 'Ok'],
        ['Ok', 'Ok', 'Ok', 'Ok', 'Ok']],

       [['Ok', 'Ok', 'Ok', 'Ok', 'Ok'],
        ['Ok', 'Ok', 'Ok', 'Ok', 'Ok'],
        ['Ok', 'Ok', 'Ok', 'Ok', 'Ok']]], dtype='<U5')

Datos aleatorios

In [ ]:
datos=np.random.randint(0,50,40)
print(datos)

[46 16 48 42 32 39 41 32 33 14 49 35 27 48 12  2 45 13 24  2 46 34 16  0
 39 20  9 36 44 38 44 41 39 30  1  8 13 47 21 21]


In [ ]:
data=np.reshape(datos,(8,5))
print(data)

[[46 16 48 42 32]
 [39 41 32 33 14]
 [49 35 27 48 12]
 [ 2 45 13 24  2]
 [46 34 16  0 39]
 [20  9 36 44 38]
 [44 41 39 30  1]
 [ 8 13 47 21 21]]


In [ ]:
data1=np.random.randint(0,100,100).reshape(10,10)
print(data1)

[[52 18 32  2 64 17 89  4  1 84]
 [81 61 13 55 42 17 91 10 84 85]
 [96 51  4 85 27 66 42 97  2  4]
 [29 71 70 57 49 34 43 13 42 45]
 [74 88  4 38 15 38 91 98 76 87]
 [17 22 38  7 17 20  8  2 20 57]
 [93  1 59 48 46 30 82 14 40 27]
 [59 81  9 92 72 46 60 71 41 67]
 [23 59 25 43 51 60  4 33 99 45]
 [35 18 61 32 72  8 57 30 15 73]]


In [ ]:
print(np.where(data1>=50, "Ok", "No Ok"))

[['Ok' 'No Ok' 'No Ok' 'No Ok' 'Ok' 'No Ok' 'Ok' 'No Ok' 'No Ok' 'Ok']
 ['Ok' 'Ok' 'No Ok' 'Ok' 'No Ok' 'No Ok' 'Ok' 'No Ok' 'Ok' 'Ok']
 ['Ok' 'Ok' 'No Ok' 'Ok' 'No Ok' 'Ok' 'No Ok' 'Ok' 'No Ok' 'No Ok']
 ['No Ok' 'Ok' 'Ok' 'Ok' 'No Ok' 'No Ok' 'No Ok' 'No Ok' 'No Ok' 'No Ok']
 ['Ok' 'Ok' 'No Ok' 'No Ok' 'No Ok' 'No Ok' 'Ok' 'Ok' 'Ok' 'Ok']
 ['No Ok' 'No Ok' 'No Ok' 'No Ok' 'No Ok' 'No Ok' 'No Ok' 'No Ok' 'No Ok'
  'Ok']
 ['Ok' 'No Ok' 'Ok' 'No Ok' 'No Ok' 'No Ok' 'Ok' 'No Ok' 'No Ok' 'No Ok']
 ['Ok' 'Ok' 'No Ok' 'Ok' 'Ok' 'No Ok' 'Ok' 'Ok' 'No Ok' 'Ok']
 ['No Ok' 'Ok' 'No Ok' 'No Ok' 'Ok' 'Ok' 'No Ok' 'No Ok' 'Ok' 'No Ok']
 ['No Ok' 'No Ok' 'Ok' 'No Ok' 'Ok' 'No Ok' 'Ok' 'No Ok' 'No Ok' 'Ok']]


In [ ]:
data3=np.random.rand(100).reshape(20,5)
print(data3)

[[0.77275933 0.68925522 0.70384541 0.42022581 0.32819837]
 [0.73341398 0.59572563 0.85319181 0.48356011 0.08289927]
 [0.58705667 0.89438666 0.21714078 0.15922259 0.81750629]
 [0.95225109 0.59142136 0.38051838 0.44773831 0.7786816 ]
 [0.21727254 0.62262628 0.02272979 0.63109355 0.44293121]
 [0.76692831 0.83139857 0.89234025 0.70606292 0.22858144]
 [0.80901595 0.72927081 0.73574091 0.17904043 0.80801305]
 [0.08962831 0.46414333 0.34068857 0.67787901 0.08423826]
 [0.01065901 0.37412107 0.43637837 0.30191951 0.18643642]
 [0.08459319 0.41940441 0.77329309 0.62754916 0.75678673]
 [0.41880552 0.0596547  0.15897755 0.87414191 0.84071485]
 [0.76051316 0.62716498 0.19766925 0.02272849 0.79778732]
 [0.09725355 0.18828508 0.05964153 0.97006315 0.26624026]
 [0.35574515 0.55425327 0.22641263 0.68781025 0.21524603]
 [0.77541482 0.58409455 0.40486376 0.80316159 0.55937178]
 [0.4129939  0.45590413 0.50140872 0.98469448 0.83030358]
 [0.90664326 0.55079582 0.69447956 0.06777817 0.48837398]
 [0.4469106  0