<a href="https://colab.research.google.com/github/ManuelRomero2025/Programaci-nPython20254/blob/main/Ejemplos_series_dataframe_paneles_pandas_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Curso práctico: Series, DataFrame y Paneles 3D en Pandas y NumPy

Este cuaderno organiza todos los ejemplos desarrollados en el chat y los amplía con procesos de manipulación de datos y análisis estadístico básico. Se trabaja desde estructuras simples como `Series`, hasta `DataFrame`, matrices 2D y paneles 3D representados mediante `MultiIndex`.

## Objetivos

1. Comprender la estructura de una `Series` de Pandas.
2. Crear `DataFrame` desde diccionarios, listas de listas y listas de diccionarios.
3. Convertir tipos de datos usando `pd.to_numeric()`.
4. Simular datos con NumPy y convertirlos en tablas etiquetadas.
5. Representar paneles 3D como tablas con índice jerárquico.
6. Aplicar procesos estadísticos y de manipulación adecuados según el tipo de estructura.


In [1]:
# ============================================================
# LIBRERÍAS BASE
# ============================================================

import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 120)

print('Librerías cargadas correctamente')

Librerías cargadas correctamente


## Tabla guía de estructuras

| Estructura | Dimensión | Forma conceptual | Ejemplo típico | Uso principal |
|---|---:|---|---|---|
| Series | 1D | Vector con índice | Ventas por mes | Variable individual |
| DataFrame | 2D | Tabla de filas y columnas | Estudiantes × variables | Base de datos tabular |
| Matriz NumPy | 2D | Filas × columnas | Clientes × meses | Simulación y álgebra |
| Panel 3D | 3D | Elementos × tiempo × variables | Clientes × meses × indicadores | Datos longitudinales/multivariados |
| DataFrame MultiIndex | 2D con índice jerárquico | Tabla larga con varios niveles | Cliente–Mes | Análisis de panel en Pandas |


# 1. Series de Pandas

Una `Series` es una estructura unidimensional con valores e índice. En ciencia de datos representa una variable individual: ventas, notas, temperaturas, precios, clientes, entre otras.


In [ ]:
# Ejemplo base 1: Series de países
s = pd.Series(['Colombia', 'Argentina', 'Uruguay', 'Brasil', 'USA'], dtype='string')
print(s)
print('\nTipo de dato:')
print(s.dtype)

0     Colombia
1    Argentina
2      Uruguay
3       Brasil
4          USA
dtype: string

Tipo de dato:
string


In [ ]:
# Ejemplo base 2: Series desde diccionario
s1 = pd.Series({'Colombia': 6.0, 'Argentina': 4.5, 'Uruguay': 8.5, 'Brasil': 5.0, 'USA': 5.0})
print(s1)
print('\nEstadísticos descriptivos:')
print(s1.describe())

Colombia     6.0
Argentina    4.5
Uruguay      8.5
Brasil       5.0
USA          5.0
dtype: float64

Estadísticos descriptivos:
count    5.000000
mean     5.800000
std      1.604681
min      4.500000
25%      5.000000
50%      5.000000
75%      6.000000
max      8.500000
dtype: float64


## 1.1. Ventas mensuales

Representa ventas mensuales de una empresa. Permite calcular promedio, máximo, mínimo y detectar meses destacados.


In [ ]:
ventas = pd.Series([1200, 1500, 1800, 1700, 2100, 2500], index=['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio'])
print(ventas)

print('\nEstadísticos descriptivos:')
print(ventas.describe())

print('\nMayor valor:')
print(ventas.idxmax(), ventas.max())

print('\nFiltro de valores superiores al promedio:')
print(ventas[ventas > ventas.mean()])

Enero      1200
Febrero    1500
Marzo      1800
Abril      1700
Mayo       2100
Junio      2500
dtype: int64

Estadísticos descriptivos:
count       6.00000
mean     1800.00000
std       456.07017
min      1200.00000
25%      1550.00000
50%      1750.00000
75%      2025.00000
max      2500.00000
dtype: float64

Mayor valor:
Junio 2500

Filtro de valores superiores al promedio:
Mayo     2100
Junio    2500
dtype: int64


## 1.2. Temperaturas semanales

Representa temperaturas registradas durante una semana. Es útil para análisis ambiental y series temporales.


In [ ]:
temperaturas = pd.Series([18, 20, 19, 22, 24, 21, 20], index=['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'])
print(temperaturas)

print('\nEstadísticos descriptivos:')
print(temperaturas.describe())

print('\nMayor valor:')
print(temperaturas.idxmax(), temperaturas.max())

print('\nFiltro de valores superiores al promedio:')
print(temperaturas[temperaturas > temperaturas.mean()])

Lunes        18
Martes       20
Miércoles    19
Jueves       22
Viernes      24
Sábado       21
Domingo      20
dtype: int64

Estadísticos descriptivos:
count     7.000000
mean     20.571429
std       1.988060
min      18.000000
25%      19.500000
50%      20.000000
75%      21.500000
max      24.000000
dtype: float64

Mayor valor:
Viernes 24

Filtro de valores superiores al promedio:
Jueves     22
Viernes    24
Sábado     21
dtype: int64


## 1.3. Calificaciones de estudiantes

Representa notas de estudiantes. Permite identificar rendimiento promedio y estudiantes destacados.


In [ ]:
notas = pd.Series({'Juan': 4.5, 'Ana': 3.8, 'Carlos': 4.9, 'Luisa': 4.2, 'Pedro': 2.9})
print(notas)

print('\nEstadísticos descriptivos:')
print(notas.describe())

print('\nMayor valor:')
print(notas.idxmax(), notas.max())

print('\nOrden descendente:')
print(notas.sort_values(ascending=False))

Juan      4.5
Ana       3.8
Carlos    4.9
Luisa     4.2
Pedro     2.9
dtype: float64

Estadísticos descriptivos:
count    5.000000
mean     4.060000
std      0.763544
min      2.900000
25%      3.800000
50%      4.200000
75%      4.500000
max      4.900000
dtype: float64

Mayor valor:
Carlos 4.9

Orden descendente:
Carlos    4.9
Juan      4.5
Luisa     4.2
Ana       3.8
Pedro     2.9
dtype: float64


## 1.4. Precio de acciones

Representa precios financieros por día. Permite calcular variación y precio promedio.


In [ ]:
acciones = pd.Series([1050, 1080, 1105, 1090, 1120], index=['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'])
print(acciones)

print('\nEstadísticos descriptivos:')
print(acciones.describe())

print('\nMayor valor:')
print(acciones.idxmax(), acciones.max())

print('\nFiltro de valores superiores al promedio:')
print(acciones[acciones > acciones.mean()])

Lunes        1050
Martes       1080
Miércoles    1105
Jueves       1090
Viernes      1120
dtype: int64

Estadísticos descriptivos:
count       5.000000
mean     1089.000000
std        26.551836
min      1050.000000
25%      1080.000000
50%      1090.000000
75%      1105.000000
max      1120.000000
dtype: float64

Mayor valor:
Viernes 1120

Filtro de valores superiores al promedio:
Miércoles    1105
Jueves       1090
Viernes      1120
dtype: int64


## 1.5. Clientes por sucursal

Representa número de clientes por ciudad. Es útil para inteligencia de negocios y análisis regional.


In [ ]:
clientes = pd.Series([250, 180, 320, 150, 290], index=['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena'])
print(clientes)

print('\nEstadísticos descriptivos:')
print(clientes.describe())

print('\nMayor valor:')
print(clientes.idxmax(), clientes.max())

print('\nFiltro de valores superiores al promedio:')
print(clientes[clientes > clientes.mean()])

Bogotá          250
Medellín        180
Cali            320
Barranquilla    150
Cartagena       290
dtype: int64

Estadísticos descriptivos:
count      5.000000
mean     238.000000
std       71.902712
min      150.000000
25%      180.000000
50%      250.000000
75%      290.000000
max      320.000000
dtype: float64

Mayor valor:
Cali 320

Filtro de valores superiores al promedio:
Bogotá       250
Cali         320
Cartagena    290
dtype: int64


# 2. DataFrame desde diccionarios

En esta estructura, cada clave del diccionario representa una columna. Es una de las formas más utilizadas para construir tablas pequeñas o bases simuladas.


In [ ]:
# Ejemplo base: DataFrame desde diccionario

datos = {
    'nombre': ['Cali', 'Medellin', 'Bogotá', 'Barranquilla'],
    'edad': [18, 22, 20, 21],
    'grado': ['Economía', 'Medicina', 'Arquitectura', 'Economía']
}

df_base_diccionario = pd.DataFrame(datos, dtype='string')
print(df_base_diccionario)
print('\nTipos de datos:')
print(df_base_diccionario.dtypes)

         nombre edad         grado
0          Cali   18      Economía
1      Medellin   22      Medicina
2        Bogotá   20  Arquitectura
3  Barranquilla   21      Economía

Tipos de datos:
nombre    string[python]
edad      string[python]
grado     string[python]
dtype: object


## 2.1. Información de estudiantes

Aplicación: análisis tabular, estadísticas descriptivas, filtros y agrupaciones según variables categóricas.


In [ ]:
df_estudiantes = pd.DataFrame({'Nombre': ['Ana', 'Carlos', 'Luisa', 'Pedro'], 'Edad': [18, 20, 19, 21], 'Carrera': ['Economía', 'Ingeniería', 'Medicina', 'Derecho']})
print(df_estudiantes)
print('\nTipos de datos:')
print(df_estudiantes.dtypes)
print('\nResumen estadístico:')
print(df_estudiantes.describe(include='all'))
print('\nAgrupación o conteo por variable categórica:')
print(df_estudiantes['Carrera'].value_counts())
print('\nFiltro: valores numéricos superiores al promedio')
print(df_estudiantes[df_estudiantes['Edad'] > df_estudiantes['Edad'].mean()])

   Nombre  Edad     Carrera
0     Ana    18    Economía
1  Carlos    20  Ingeniería
2   Luisa    19    Medicina
3   Pedro    21     Derecho

Tipos de datos:
Nombre     object
Edad        int64
Carrera    object
dtype: object

Resumen estadístico:
       Nombre       Edad   Carrera
count       4   4.000000         4
unique      4        NaN         4
top       Ana        NaN  Economía
freq        1        NaN         1
mean      NaN  19.500000       NaN
std       NaN   1.290994       NaN
min       NaN  18.000000       NaN
25%       NaN  18.750000       NaN
50%       NaN  19.500000       NaN
75%       NaN  20.250000       NaN
max       NaN  21.000000       NaN

Agrupación o conteo por variable categórica:
Carrera
Economía      1
Ingeniería    1
Medicina      1
Derecho       1
Name: count, dtype: int64

Filtro: valores numéricos superiores al promedio
   Nombre  Edad     Carrera
1  Carlos    20  Ingeniería
3   Pedro    21     Derecho


## 2.2. Ventas de una tienda

Aplicación: análisis tabular, estadísticas descriptivas, filtros y agrupaciones según variables categóricas.


In [ ]:
df_ventas = pd.DataFrame({'Producto': ['Laptop', 'Mouse', 'Teclado', 'Monitor'], 'Precio': [3500, 80, 150, 900], 'Cantidad': [5, 20, 15, 7]})
print(df_ventas)
print('\nTipos de datos:')
print(df_ventas.dtypes)
print('\nResumen estadístico:')
print(df_ventas.describe(include='all'))
print('\nAgrupación o conteo por variable categórica:')
print(df_ventas['Producto'].value_counts())
print('\nFiltro: valores numéricos superiores al promedio')
print(df_ventas[df_ventas['Precio'] > df_ventas['Precio'].mean()])

  Producto  Precio  Cantidad
0   Laptop    3500         5
1    Mouse      80        20
2  Teclado     150        15
3  Monitor     900         7

Tipos de datos:
Producto    object
Precio       int64
Cantidad     int64
dtype: object

Resumen estadístico:
       Producto       Precio   Cantidad
count         4     4.000000   4.000000
unique        4          NaN        NaN
top      Laptop          NaN        NaN
freq          1          NaN        NaN
mean        NaN  1157.500000  11.750000
std         NaN  1605.166139   6.994045
min         NaN    80.000000   5.000000
25%         NaN   132.500000   6.500000
50%         NaN   525.000000  11.000000
75%         NaN  1550.000000  16.250000
max         NaN  3500.000000  20.000000

Agrupación o conteo por variable categórica:
Producto
Laptop     1
Mouse      1
Teclado    1
Monitor    1
Name: count, dtype: int64

Filtro: valores numéricos superiores al promedio
  Producto  Precio  Cantidad
0   Laptop    3500         5


## 2.3. Datos climáticos

Aplicación: análisis tabular, estadísticas descriptivas, filtros y agrupaciones según variables categóricas.


In [ ]:
df_clima = pd.DataFrame({'Ciudad': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla'], 'Temperatura': [18, 24, 28, 32], 'Humedad': [75, 65, 70, 80]})
print(df_clima)
print('\nTipos de datos:')
print(df_clima.dtypes)
print('\nResumen estadístico:')
print(df_clima.describe(include='all'))
print('\nAgrupación o conteo por variable categórica:')
print(df_clima['Ciudad'].value_counts())
print('\nFiltro: valores numéricos superiores al promedio')
print(df_clima[df_clima['Temperatura'] > df_clima['Temperatura'].mean()])

         Ciudad  Temperatura  Humedad
0        Bogotá           18       75
1      Medellín           24       65
2          Cali           28       70
3  Barranquilla           32       80

Tipos de datos:
Ciudad         object
Temperatura     int64
Humedad         int64
dtype: object

Resumen estadístico:
        Ciudad  Temperatura    Humedad
count        4     4.000000   4.000000
unique       4          NaN        NaN
top     Bogotá          NaN        NaN
freq         1          NaN        NaN
mean       NaN    25.500000  72.500000
std        NaN     5.972158   6.454972
min        NaN    18.000000  65.000000
25%        NaN    22.500000  68.750000
50%        NaN    26.000000  72.500000
75%        NaN    29.000000  76.250000
max        NaN    32.000000  80.000000

Agrupación o conteo por variable categórica:
Ciudad
Bogotá          1
Medellín        1
Cali            1
Barranquilla    1
Name: count, dtype: int64

Filtro: valores numéricos superiores al promedio
         Ciudad  Tempe

## 2.4. Información financiera

Aplicación: análisis tabular, estadísticas descriptivas, filtros y agrupaciones según variables categóricas.


In [ ]:
df_finanzas = pd.DataFrame({'Empresa': ['A', 'B', 'C', 'D'], 'Ingresos': [50000, 70000, 65000, 80000], 'Gastos': [30000, 40000, 35000, 50000]})
print(df_finanzas)
print('\nTipos de datos:')
print(df_finanzas.dtypes)
print('\nResumen estadístico:')
print(df_finanzas.describe(include='all'))
print('\nAgrupación o conteo por variable categórica:')
print(df_finanzas['Empresa'].value_counts())
print('\nFiltro: valores numéricos superiores al promedio')
print(df_finanzas[df_finanzas['Ingresos'] > df_finanzas['Ingresos'].mean()])

  Empresa  Ingresos  Gastos
0       A     50000   30000
1       B     70000   40000
2       C     65000   35000
3       D     80000   50000

Tipos de datos:
Empresa     object
Ingresos     int64
Gastos       int64
dtype: object

Resumen estadístico:
       Empresa  Ingresos        Gastos
count        4       4.0      4.000000
unique       4       NaN           NaN
top          A       NaN           NaN
freq         1       NaN           NaN
mean       NaN   66250.0  38750.000000
std        NaN   12500.0   8539.125638
min        NaN   50000.0  30000.000000
25%        NaN   61250.0  33750.000000
50%        NaN   67500.0  37500.000000
75%        NaN   72500.0  42500.000000
max        NaN   80000.0  50000.000000

Agrupación o conteo por variable categórica:
Empresa
A    1
B    1
C    1
D    1
Name: count, dtype: int64

Filtro: valores numéricos superiores al promedio
  Empresa  Ingresos  Gastos
1       B     70000   40000
3       D     80000   50000


## 2.5. Pacientes de un hospital

Aplicación: análisis tabular, estadísticas descriptivas, filtros y agrupaciones según variables categóricas.


In [ ]:
df_hospital = pd.DataFrame({'Paciente': ['Juan', 'María', 'Carlos', 'Laura'], 'Edad': [45, 50, 38, 60], 'Diagnóstico': ['Diabetes', 'Hipertensión', 'Asma', 'Diabetes']})
print(df_hospital)
print('\nTipos de datos:')
print(df_hospital.dtypes)
print('\nResumen estadístico:')
print(df_hospital.describe(include='all'))
print('\nAgrupación o conteo por variable categórica:')
print(df_hospital['Diagnóstico'].value_counts())
print('\nFiltro: valores numéricos superiores al promedio')
print(df_hospital[df_hospital['Edad'] > df_hospital['Edad'].mean()])

  Paciente  Edad   Diagnóstico
0     Juan    45      Diabetes
1    María    50  Hipertensión
2   Carlos    38          Asma
3    Laura    60      Diabetes

Tipos de datos:
Paciente       object
Edad            int64
Diagnóstico    object
dtype: object

Resumen estadístico:
       Paciente       Edad Diagnóstico
count         4   4.000000           4
unique        4        NaN           3
top        Juan        NaN    Diabetes
freq          1        NaN           2
mean        NaN  48.250000         NaN
std         NaN   9.251126         NaN
min         NaN  38.000000         NaN
25%         NaN  43.250000         NaN
50%         NaN  47.500000         NaN
75%         NaN  52.500000         NaN
max         NaN  60.000000         NaN

Agrupación o conteo por variable categórica:
Diagnóstico
Diabetes        2
Hipertensión    1
Asma            1
Name: count, dtype: int64

Filtro: valores numéricos superiores al promedio
  Paciente  Edad   Diagnóstico
1    María    50  Hipertensión
3    Lau

# 3. DataFrame desde listas de listas

En esta estructura, cada sublista representa una fila y el argumento `columns=` define los nombres de las columnas.


In [ ]:
# Ejemplo base: lista de listas

df_base_lista = pd.DataFrame([
    ['Manuel', 18],
    ['Ginna', 22],
    ['Sandra', 20],
    ['Paola', 20]
], columns=['Nombre', 'Edad'])

print(df_base_lista)
print(df_base_lista.dtypes)

   Nombre  Edad
0  Manuel    18
1   Ginna    22
2  Sandra    20
3   Paola    20
Nombre    object
Edad       int64
dtype: object


## 3.1. Calificaciones de estudiantes

Aplicación: construcción manual de datos pequeños, registros de clase, inventarios, sensores o datos simples por filas.


In [ ]:
df_notas = pd.DataFrame([['Ana', 4.5], ['Luis', 3.8], ['Pedro', 4.9], ['Luisa', 4.2]], columns=['Nombre', 'Nota'])
print(df_notas)
print('\nResumen estadístico:')
print(df_notas.describe(include='all'))
print('\nOrden descendente por variable numérica:')
print(df_notas.sort_values(by='Nota', ascending=False))
print('\nNueva columna estandarizada:')
df_notas['Nota_z'] = (df_notas['Nota'] - df_notas['Nota'].mean()) / df_notas['Nota'].std(ddof=1)
print(df_notas)

  Nombre  Nota
0    Ana   4.5
1   Luis   3.8
2  Pedro   4.9
3  Luisa   4.2

Resumen estadístico:
       Nombre      Nota
count       4  4.000000
unique      4       NaN
top       Ana       NaN
freq        1       NaN
mean      NaN  4.350000
std       NaN  0.465475
min       NaN  3.800000
25%       NaN  4.100000
50%       NaN  4.350000
75%       NaN  4.600000
max       NaN  4.900000

Orden descendente por variable numérica:
  Nombre  Nota
2  Pedro   4.9
0    Ana   4.5
3  Luisa   4.2
1   Luis   3.8

Nueva columna estandarizada:
  Nombre  Nota    Nota_z
0    Ana   4.5  0.322252
1   Luis   3.8 -1.181590
2  Pedro   4.9  1.181590
3  Luisa   4.2 -0.322252


## 3.2. Productos tecnológicos

Aplicación: construcción manual de datos pequeños, registros de clase, inventarios, sensores o datos simples por filas.


In [ ]:
df_productos = pd.DataFrame([['Laptop', 3500], ['Tablet', 1200], ['Celular', 2200], ['Monitor', 900]], columns=['Producto', 'Precio'])
print(df_productos)
print('\nResumen estadístico:')
print(df_productos.describe(include='all'))
print('\nOrden descendente por variable numérica:')
print(df_productos.sort_values(by='Precio', ascending=False))
print('\nNueva columna estandarizada:')
df_productos['Precio_z'] = (df_productos['Precio'] - df_productos['Precio'].mean()) / df_productos['Precio'].std(ddof=1)
print(df_productos)

  Producto  Precio
0   Laptop    3500
1   Tablet    1200
2  Celular    2200
3  Monitor     900

Resumen estadístico:
       Producto       Precio
count         4     4.000000
unique        4          NaN
top      Laptop          NaN
freq          1          NaN
mean        NaN  1950.000000
std         NaN  1173.314394
min         NaN   900.000000
25%         NaN  1125.000000
50%         NaN  1700.000000
75%         NaN  2525.000000
max         NaN  3500.000000

Orden descendente por variable numérica:
  Producto  Precio
0   Laptop    3500
2  Celular    2200
1   Tablet    1200
3  Monitor     900

Nueva columna estandarizada:
  Producto  Precio  Precio_z
0   Laptop    3500  1.321044
1   Tablet    1200 -0.639215
2  Celular    2200  0.213072
3  Monitor     900 -0.894901


## 3.3. Datos deportivos

Aplicación: construcción manual de datos pequeños, registros de clase, inventarios, sensores o datos simples por filas.


In [ ]:
df_deportes = pd.DataFrame([['Colombia', 3], ['Argentina', 2], ['Brasil', 4], ['Uruguay', 1]], columns=['Selección', 'Goles'])
print(df_deportes)
print('\nResumen estadístico:')
print(df_deportes.describe(include='all'))
print('\nOrden descendente por variable numérica:')
print(df_deportes.sort_values(by='Goles', ascending=False))
print('\nNueva columna estandarizada:')
df_deportes['Goles_z'] = (df_deportes['Goles'] - df_deportes['Goles'].mean()) / df_deportes['Goles'].std(ddof=1)
print(df_deportes)

   Selección  Goles
0   Colombia      3
1  Argentina      2
2     Brasil      4
3    Uruguay      1

Resumen estadístico:
       Selección     Goles
count          4  4.000000
unique         4       NaN
top     Colombia       NaN
freq           1       NaN
mean         NaN  2.500000
std          NaN  1.290994
min          NaN  1.000000
25%          NaN  1.750000
50%          NaN  2.500000
75%          NaN  3.250000
max          NaN  4.000000

Orden descendente por variable numérica:
   Selección  Goles
2     Brasil      4
0   Colombia      3
1  Argentina      2
3    Uruguay      1

Nueva columna estandarizada:
   Selección  Goles   Goles_z
0   Colombia      3  0.387298
1  Argentina      2 -0.387298
2     Brasil      4  1.161895
3    Uruguay      1 -1.161895


## 3.4. Empleados de una empresa

Aplicación: construcción manual de datos pequeños, registros de clase, inventarios, sensores o datos simples por filas.


In [ ]:
df_empleados = pd.DataFrame([['Carlos', 2500], ['María', 3200], ['Pedro', 2800], ['Sandra', 4100]], columns=['Empleado', 'Salario'])
print(df_empleados)
print('\nResumen estadístico:')
print(df_empleados.describe(include='all'))
print('\nOrden descendente por variable numérica:')
print(df_empleados.sort_values(by='Salario', ascending=False))
print('\nNueva columna estandarizada:')
df_empleados['Salario_z'] = (df_empleados['Salario'] - df_empleados['Salario'].mean()) / df_empleados['Salario'].std(ddof=1)
print(df_empleados)

  Empleado  Salario
0   Carlos     2500
1    María     3200
2    Pedro     2800
3   Sandra     4100

Resumen estadístico:
       Empleado      Salario
count         4     4.000000
unique        4          NaN
top      Carlos          NaN
freq          1          NaN
mean        NaN  3150.000000
std         NaN   695.221787
min         NaN  2500.000000
25%         NaN  2725.000000
50%         NaN  3000.000000
75%         NaN  3425.000000
max         NaN  4100.000000

Orden descendente por variable numérica:
  Empleado  Salario
3   Sandra     4100
1    María     3200
2    Pedro     2800
0   Carlos     2500

Nueva columna estandarizada:
  Empleado  Salario  Salario_z
0   Carlos     2500  -0.934953
1    María     3200   0.071919
2    Pedro     2800  -0.503436
3   Sandra     4100   1.366470


## 3.5. Sensores IoT

Aplicación: construcción manual de datos pequeños, registros de clase, inventarios, sensores o datos simples por filas.


In [ ]:
df_sensores = pd.DataFrame([['Sensor1', 35], ['Sensor2', 40], ['Sensor3', 38], ['Sensor4', 36]], columns=['Sensor', 'Temperatura'])
print(df_sensores)
print('\nResumen estadístico:')
print(df_sensores.describe(include='all'))
print('\nOrden descendente por variable numérica:')
print(df_sensores.sort_values(by='Temperatura', ascending=False))
print('\nNueva columna estandarizada:')
df_sensores['Temperatura_z'] = (df_sensores['Temperatura'] - df_sensores['Temperatura'].mean()) / df_sensores['Temperatura'].std(ddof=1)
print(df_sensores)

    Sensor  Temperatura
0  Sensor1           35
1  Sensor2           40
2  Sensor3           38
3  Sensor4           36

Resumen estadístico:
         Sensor  Temperatura
count         4     4.000000
unique        4          NaN
top     Sensor1          NaN
freq          1          NaN
mean        NaN    37.250000
std         NaN     2.217356
min         NaN    35.000000
25%         NaN    35.750000
50%         NaN    37.000000
75%         NaN    38.500000
max         NaN    40.000000

Orden descendente por variable numérica:
    Sensor  Temperatura
1  Sensor2           40
2  Sensor3           38
3  Sensor4           36
0  Sensor1           35

Nueva columna estandarizada:
    Sensor  Temperatura  Temperatura_z
0  Sensor1           35      -1.014722
1  Sensor2           40       1.240216
2  Sensor3           38       0.338241
3  Sensor4           36      -0.563735


# 4. DataFrame desde lista de diccionarios

Cada diccionario representa una fila. Esta estructura es muy frecuente cuando los datos provienen de APIs, archivos JSON o registros web.


In [ ]:
# Ejemplo base: lista de diccionarios

df_base_listadict = pd.DataFrame([
    {'Nombre': 'María', 'Edad': 18},
    {'Nombre': 'Luis', 'Edad': 22},
    {'Nombre': 'Luisa', 'Edad': 22},
    {'Nombre': 'Carlos', 'Edad': 20}
])

print(df_base_listadict)
print(df_base_listadict.dtypes)

   Nombre  Edad
0   María    18
1    Luis    22
2   Luisa    22
3  Carlos    20
Nombre    object
Edad       int64
dtype: object


## 4.1. Clientes bancarios

Aplicación: datos tipo JSON/API, registros flexibles y procesamiento tabular con Pandas.


In [ ]:
df_banco = pd.DataFrame([{'Cliente': 'Ana', 'Saldo': 5000}, {'Cliente': 'Luis', 'Saldo': 3200}, {'Cliente': 'Pedro', 'Saldo': 4100}, {'Cliente': 'Laura', 'Saldo': 2800}])
print(df_banco)
print('\nTipos de datos:')
print(df_banco.dtypes)
print('\nResumen estadístico:')
print(df_banco.describe(include='all'))
print('\nVariable normalizada entre 0 y 1:')
df_banco['Saldo_minmax'] = (df_banco['Saldo'] - df_banco['Saldo'].min()) / (df_banco['Saldo'].max() - df_banco['Saldo'].min())
print(df_banco)

  Cliente  Saldo
0     Ana   5000
1    Luis   3200
2   Pedro   4100
3   Laura   2800

Tipos de datos:
Cliente    object
Saldo       int64
dtype: object

Resumen estadístico:
       Cliente        Saldo
count        4     4.000000
unique       4          NaN
top        Ana          NaN
freq         1          NaN
mean       NaN  3775.000000
std        NaN   981.070844
min        NaN  2800.000000
25%        NaN  3100.000000
50%        NaN  3650.000000
75%        NaN  4325.000000
max        NaN  5000.000000

Variable normalizada entre 0 y 1:
  Cliente  Saldo  Saldo_minmax
0     Ana   5000      1.000000
1    Luis   3200      0.181818
2   Pedro   4100      0.590909
3   Laura   2800      0.000000


## 4.2. Inventario de productos

Aplicación: datos tipo JSON/API, registros flexibles y procesamiento tabular con Pandas.


In [ ]:
df_inventario = pd.DataFrame([{'Producto': 'Mouse', 'Stock': 50}, {'Producto': 'Teclado', 'Stock': 30}, {'Producto': 'Monitor', 'Stock': 20}, {'Producto': 'Laptop', 'Stock': 10}])
print(df_inventario)
print('\nTipos de datos:')
print(df_inventario.dtypes)
print('\nResumen estadístico:')
print(df_inventario.describe(include='all'))
print('\nVariable normalizada entre 0 y 1:')
df_inventario['Stock_minmax'] = (df_inventario['Stock'] - df_inventario['Stock'].min()) / (df_inventario['Stock'].max() - df_inventario['Stock'].min())
print(df_inventario)

  Producto  Stock
0    Mouse     50
1  Teclado     30
2  Monitor     20
3   Laptop     10

Tipos de datos:
Producto    object
Stock        int64
dtype: object

Resumen estadístico:
       Producto      Stock
count         4   4.000000
unique        4        NaN
top       Mouse        NaN
freq          1        NaN
mean        NaN  27.500000
std         NaN  17.078251
min         NaN  10.000000
25%         NaN  17.500000
50%         NaN  25.000000
75%         NaN  35.000000
max         NaN  50.000000

Variable normalizada entre 0 y 1:
  Producto  Stock  Stock_minmax
0    Mouse     50          1.00
1  Teclado     30          0.50
2  Monitor     20          0.25
3   Laptop     10          0.00


## 4.3. Datos médicos

Aplicación: datos tipo JSON/API, registros flexibles y procesamiento tabular con Pandas.


In [ ]:
df_medico = pd.DataFrame([{'Paciente': 'Juan', 'Presión': 120}, {'Paciente': 'María', 'Presión': 130}, {'Paciente': 'Carlos', 'Presión': 110}, {'Paciente': 'Luisa', 'Presión': 125}])
print(df_medico)
print('\nTipos de datos:')
print(df_medico.dtypes)
print('\nResumen estadístico:')
print(df_medico.describe(include='all'))
print('\nVariable normalizada entre 0 y 1:')
df_medico['Presión_minmax'] = (df_medico['Presión'] - df_medico['Presión'].min()) / (df_medico['Presión'].max() - df_medico['Presión'].min())
print(df_medico)

  Paciente  Presión
0     Juan      120
1    María      130
2   Carlos      110
3    Luisa      125

Tipos de datos:
Paciente    object
Presión      int64
dtype: object

Resumen estadístico:
       Paciente     Presión
count         4    4.000000
unique        4         NaN
top        Juan         NaN
freq          1         NaN
mean        NaN  121.250000
std         NaN    8.539126
min         NaN  110.000000
25%         NaN  117.500000
50%         NaN  122.500000
75%         NaN  126.250000
max         NaN  130.000000

Variable normalizada entre 0 y 1:
  Paciente  Presión  Presión_minmax
0     Juan      120            0.50
1    María      130            1.00
2   Carlos      110            0.00
3    Luisa      125            0.75


## 4.4. Información de vehículos

Aplicación: datos tipo JSON/API, registros flexibles y procesamiento tabular con Pandas.


In [ ]:
df_vehiculos = pd.DataFrame([{'Marca': 'Toyota', 'Año': 2020}, {'Marca': 'Mazda', 'Año': 2021}, {'Marca': 'Ford', 'Año': 2019}, {'Marca': 'Kia', 'Año': 2022}])
print(df_vehiculos)
print('\nTipos de datos:')
print(df_vehiculos.dtypes)
print('\nResumen estadístico:')
print(df_vehiculos.describe(include='all'))
print('\nVariable normalizada entre 0 y 1:')
df_vehiculos['Año_minmax'] = (df_vehiculos['Año'] - df_vehiculos['Año'].min()) / (df_vehiculos['Año'].max() - df_vehiculos['Año'].min())
print(df_vehiculos)

    Marca   Año
0  Toyota  2020
1   Mazda  2021
2    Ford  2019
3     Kia  2022

Tipos de datos:
Marca    object
Año       int64
dtype: object

Resumen estadístico:
         Marca          Año
count        4     4.000000
unique       4          NaN
top     Toyota          NaN
freq         1          NaN
mean       NaN  2020.500000
std        NaN     1.290994
min        NaN  2019.000000
25%        NaN  2019.750000
50%        NaN  2020.500000
75%        NaN  2021.250000
max        NaN  2022.000000

Variable normalizada entre 0 y 1:
    Marca   Año  Año_minmax
0  Toyota  2020    0.333333
1   Mazda  2021    0.666667
2    Ford  2019    0.000000
3     Kia  2022    1.000000


## 4.5. Redes sociales

Aplicación: datos tipo JSON/API, registros flexibles y procesamiento tabular con Pandas.


In [ ]:
df_redes = pd.DataFrame([{'Usuario': 'user1', 'Seguidores': 1200}, {'Usuario': 'user2', 'Seguidores': 5000}, {'Usuario': 'user3', 'Seguidores': 3200}, {'Usuario': 'user4', 'Seguidores': 800}])
print(df_redes)
print('\nTipos de datos:')
print(df_redes.dtypes)
print('\nResumen estadístico:')
print(df_redes.describe(include='all'))
print('\nVariable normalizada entre 0 y 1:')
df_redes['Seguidores_minmax'] = (df_redes['Seguidores'] - df_redes['Seguidores'].min()) / (df_redes['Seguidores'].max() - df_redes['Seguidores'].min())
print(df_redes)

  Usuario  Seguidores
0   user1        1200
1   user2        5000
2   user3        3200
3   user4         800

Tipos de datos:
Usuario       object
Seguidores     int64
dtype: object

Resumen estadístico:
       Usuario   Seguidores
count        4     4.000000
unique       4          NaN
top      user1          NaN
freq         1          NaN
mean       NaN  2550.000000
std        NaN  1941.648784
min        NaN   800.000000
25%        NaN  1100.000000
50%        NaN  2200.000000
75%        NaN  3650.000000
max        NaN  5000.000000

Variable normalizada entre 0 y 1:
  Usuario  Seguidores  Seguidores_minmax
0   user1        1200           0.095238
1   user2        5000           1.000000
2   user3        3200           0.571429
3   user4         800           0.000000


# 5. Conversión de tipos de datos con `pd.to_numeric()`

Cuando se crea un `DataFrame` con `dtype='string'`, todas las columnas quedan como texto. Para realizar cálculos estadísticos, las variables cuantitativas deben convertirse a tipo numérico.


In [ ]:
# Ejemplo base de conversión de tipos

datos = {
    'nombre': ['Cali', 'Medellin', 'Bogotá', 'Barranquilla'],
    'edad': [18, 22, 20, 21],
    'promedio': [4.5, 4.2, 3.9, 4.7],
    'grado': ['Economía', 'Medicina', 'Arquitectura', 'Economía']
}

df_conversion_base = pd.DataFrame(datos, dtype='string')
print(df_conversion_base)
print('\nTipos antes:')
print(df_conversion_base.dtypes)

df_conversion_base['edad'] = pd.to_numeric(df_conversion_base['edad'])
df_conversion_base['promedio'] = pd.to_numeric(df_conversion_base['promedio'])

print('\nTipos después:')
print(df_conversion_base.dtypes)
print('\nResumen estadístico:')
print(df_conversion_base.describe())

         nombre edad promedio         grado
0          Cali   18      4.5      Economía
1      Medellin   22      4.2      Medicina
2        Bogotá   20      3.9  Arquitectura
3  Barranquilla   21      4.7      Economía

Tipos antes:
nombre      string[python]
edad        string[python]
promedio    string[python]
grado       string[python]
dtype: object

Tipos después:
nombre      string[python]
edad                 Int64
promedio           Float64
grado       string[python]
dtype: object

Resumen estadístico:
           edad  promedio
count       4.0       4.0
mean      20.25     4.325
std    1.707825      0.35
min        18.0       3.9
25%        19.5     4.125
50%        20.5      4.35
75%       21.25      4.55
max        22.0       4.7


## 5.1. Empleados

Aplicación: limpieza de datos, verificación de tipos, conversión de variables cuantitativas y análisis estadístico posterior.


In [ ]:
df_emp_conv = pd.DataFrame({'empleado': ['Carlos', 'Ana', 'Pedro', 'Luisa'], 'edad': [28, 35, 30, 26], 'salario': [2500.5, 3200.0, 2800.75, 4100.2], 'departamento': ['Ventas', 'Marketing', 'Finanzas', 'TI']}, dtype='string')
print('DataFrame inicial:')
print(df_emp_conv)
print('\nTipos antes de convertir:')
print(df_emp_conv.dtypes)

df_emp_conv['edad'] = pd.to_numeric(df_emp_conv['edad'])
df_emp_conv['salario'] = pd.to_numeric(df_emp_conv['salario'])

print('\nTipos después de convertir:')
print(df_emp_conv.dtypes)
print('\nEstadísticos descriptivos de variables numéricas: edad, salario')
print(df_emp_conv[['edad', 'salario']].describe())
print('\nConteo por variable categórica:')
print(df_emp_conv['departamento'].value_counts())

DataFrame inicial:
  empleado edad  salario departamento
0   Carlos   28   2500.5       Ventas
1      Ana   35   3200.0    Marketing
2    Pedro   30  2800.75     Finanzas
3    Luisa   26   4100.2           TI

Tipos antes de convertir:
empleado        string[python]
edad            string[python]
salario         string[python]
departamento    string[python]
dtype: object

Tipos después de convertir:
empleado        string[python]
edad                     Int64
salario                Float64
departamento    string[python]
dtype: object

Estadísticos descriptivos de variables numéricas: edad, salario
          edad     salario
count      4.0         4.0
mean     29.75   3150.3625
std    3.86221  695.031253
min       26.0      2500.5
25%       27.5   2725.6875
50%       29.0    3000.375
75%      31.25     3425.05
max       35.0      4100.2

Conteo por variable categórica:
departamento
Ventas       1
Marketing    1
Finanzas     1
TI           1
Name: count, dtype: Int64


## 5.2. Productos tecnológicos

Aplicación: limpieza de datos, verificación de tipos, conversión de variables cuantitativas y análisis estadístico posterior.


In [ ]:
df_prod_conv = pd.DataFrame({'producto': ['Laptop', 'Mouse', 'Monitor', 'Tablet'], 'stock': [15, 120, 35, 40], 'precio': [3500.0, 80.5, 900.0, 1200.99], 'categoria': ['Computo', 'Accesorio', 'Pantalla', 'Movil']}, dtype='string')
print('DataFrame inicial:')
print(df_prod_conv)
print('\nTipos antes de convertir:')
print(df_prod_conv.dtypes)

df_prod_conv['stock'] = pd.to_numeric(df_prod_conv['stock'])
df_prod_conv['precio'] = pd.to_numeric(df_prod_conv['precio'])

print('\nTipos después de convertir:')
print(df_prod_conv.dtypes)
print('\nEstadísticos descriptivos de variables numéricas: stock, precio')
print(df_prod_conv[['stock', 'precio']].describe())
print('\nConteo por variable categórica:')
print(df_prod_conv['categoria'].value_counts())

DataFrame inicial:
  producto stock   precio  categoria
0   Laptop    15   3500.0    Computo
1    Mouse   120     80.5  Accesorio
2  Monitor    35    900.0   Pantalla
3   Tablet    40  1200.99      Movil

Tipos antes de convertir:
producto     string[python]
stock        string[python]
precio       string[python]
categoria    string[python]
dtype: object

Tipos después de convertir:
producto     string[python]
stock                 Int64
precio              Float64
categoria    string[python]
dtype: object

Estadísticos descriptivos de variables numéricas: stock, precio
           stock       precio
count        4.0          4.0
mean        52.5    1420.3725
std    46.278145  1465.039826
min         15.0         80.5
25%         30.0      695.125
50%         37.5     1050.495
75%         60.0    1775.7425
max        120.0       3500.0

Conteo por variable categórica:
categoria
Computo      1
Accesorio    1
Pantalla     1
Movil        1
Name: count, dtype: Int64


## 5.3. Información médica

Aplicación: limpieza de datos, verificación de tipos, conversión de variables cuantitativas y análisis estadístico posterior.


In [ ]:
df_med_conv = pd.DataFrame({'paciente': ['Juan', 'Maria', 'Carlos', 'Laura'], 'edad': [45, 52, 38, 60], 'presion': [120.5, 135.2, 118.7, 140.3], 'diagnostico': ['Diabetes', 'Hipertension', 'Asma', 'Diabetes']}, dtype='string')
print('DataFrame inicial:')
print(df_med_conv)
print('\nTipos antes de convertir:')
print(df_med_conv.dtypes)

df_med_conv['edad'] = pd.to_numeric(df_med_conv['edad'])
df_med_conv['presion'] = pd.to_numeric(df_med_conv['presion'])

print('\nTipos después de convertir:')
print(df_med_conv.dtypes)
print('\nEstadísticos descriptivos de variables numéricas: edad, presion')
print(df_med_conv[['edad', 'presion']].describe())
print('\nConteo por variable categórica:')
print(df_med_conv['diagnostico'].value_counts())

DataFrame inicial:
  paciente edad presion   diagnostico
0     Juan   45   120.5      Diabetes
1    Maria   52   135.2  Hipertension
2   Carlos   38   118.7          Asma
3    Laura   60   140.3      Diabetes

Tipos antes de convertir:
paciente       string[python]
edad           string[python]
presion        string[python]
diagnostico    string[python]
dtype: object

Tipos después de convertir:
paciente       string[python]
edad                    Int64
presion               Float64
diagnostico    string[python]
dtype: object

Estadísticos descriptivos de variables numéricas: edad, presion
           edad    presion
count       4.0        4.0
mean      48.75    128.675
std    9.429563  10.708992
min        38.0      118.7
25%       43.25     120.05
50%        48.5     127.85
75%        54.0    136.475
max        60.0      140.3

Conteo por variable categórica:
diagnostico
Diabetes        2
Hipertension    1
Asma            1
Name: count, dtype: Int64


## 5.4. Ventas empresariales

Aplicación: limpieza de datos, verificación de tipos, conversión de variables cuantitativas y análisis estadístico posterior.


In [ ]:
df_ventas_conv = pd.DataFrame({'mes': ['Enero', 'Febrero', 'Marzo', 'Abril'], 'ventas': [12000, 15000, 17000, 14000], 'ganancia': [3500.5, 4200.8, 5000.0, 3900.2], 'region': ['Norte', 'Sur', 'Centro', 'Occidente']}, dtype='string')
print('DataFrame inicial:')
print(df_ventas_conv)
print('\nTipos antes de convertir:')
print(df_ventas_conv.dtypes)

df_ventas_conv['ventas'] = pd.to_numeric(df_ventas_conv['ventas'])
df_ventas_conv['ganancia'] = pd.to_numeric(df_ventas_conv['ganancia'])

print('\nTipos después de convertir:')
print(df_ventas_conv.dtypes)
print('\nEstadísticos descriptivos de variables numéricas: ventas, ganancia')
print(df_ventas_conv[['ventas', 'ganancia']].describe())
print('\nConteo por variable categórica:')
print(df_ventas_conv['region'].value_counts())

DataFrame inicial:
       mes ventas ganancia     region
0    Enero  12000   3500.5      Norte
1  Febrero  15000   4200.8        Sur
2    Marzo  17000   5000.0     Centro
3    Abril  14000   3900.2  Occidente

Tipos antes de convertir:
mes         string[python]
ventas      string[python]
ganancia    string[python]
region      string[python]
dtype: object

Tipos después de convertir:
mes         string[python]
ventas               Int64
ganancia           Float64
region      string[python]
dtype: object

Estadísticos descriptivos de variables numéricas: ventas, ganancia
            ventas    ganancia
count          4.0         4.0
mean       14500.0    4150.375
std    2081.665999  634.909539
min        12000.0      3500.5
25%        13500.0    3800.275
50%        14500.0      4050.5
75%        15500.0      4400.6
max        17000.0      5000.0

Conteo por variable categórica:
region
Norte        1
Sur          1
Centro       1
Occidente    1
Name: count, dtype: Int64


## 5.5. Datos climáticos

Aplicación: limpieza de datos, verificación de tipos, conversión de variables cuantitativas y análisis estadístico posterior.


In [ ]:
df_clima_conv = pd.DataFrame({'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla'], 'temperatura': [18.5, 24.0, 28.2, 32.1], 'humedad': [75, 68, 70, 82], 'clima': ['Frio', 'Templado', 'Calido', 'Humedo']}, dtype='string')
print('DataFrame inicial:')
print(df_clima_conv)
print('\nTipos antes de convertir:')
print(df_clima_conv.dtypes)

df_clima_conv['temperatura'] = pd.to_numeric(df_clima_conv['temperatura'])
df_clima_conv['humedad'] = pd.to_numeric(df_clima_conv['humedad'])

print('\nTipos después de convertir:')
print(df_clima_conv.dtypes)
print('\nEstadísticos descriptivos de variables numéricas: temperatura, humedad')
print(df_clima_conv[['temperatura', 'humedad']].describe())
print('\nConteo por variable categórica:')
print(df_clima_conv['clima'].value_counts())

DataFrame inicial:
         ciudad temperatura humedad     clima
0        Bogotá        18.5      75      Frio
1      Medellín        24.0      68  Templado
2          Cali        28.2      70    Calido
3  Barranquilla        32.1      82    Humedo

Tipos antes de convertir:
ciudad         string[python]
temperatura    string[python]
humedad        string[python]
clima          string[python]
dtype: object

Tipos después de convertir:
ciudad         string[python]
temperatura           Float64
humedad                 Int64
clima          string[python]
dtype: object

Estadísticos descriptivos de variables numéricas: temperatura, humedad
       temperatura   humedad
count          4.0       4.0
mean          25.7     73.75
std       5.829237  6.238322
min           18.5      68.0
25%         22.625      69.5
50%           26.1      72.5
75%         29.175     76.75
max           32.1      82.0

Conteo por variable categórica:
clima
Frio        1
Templado    1
Calido      1
Humedo      1

# 6. Simulación con NumPy: array 1D → matriz 2D → DataFrame

Este flujo es útil para simular datos, organizarlos en forma matricial y posteriormente analizarlos con Pandas.


In [ ]:
# Ejemplo base: matriz de ingresos con etiquetas

np.random.seed(1234)
datos = np.random.uniform(2.5, 7.5, size=20)
matriz = datos.reshape(4, 5)

nombres_filas = ['Cliente A', 'Cliente B', 'Cliente C', 'Cliente D']
nombres_columnas = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo']

df_matriz_base = pd.DataFrame(matriz, index=nombres_filas, columns=nombres_columnas)

print('Matriz de ingresos con etiquetas:')
print(df_matriz_base)
print('\nPromedio por cliente:')
print(df_matriz_base.mean(axis=1))
print('\nPromedio por mes:')
print(df_matriz_base.mean(axis=0))

Matriz de ingresos con etiquetas:
              Enero   Febrero     Marzo     Abril      Mayo
Cliente A  3.457597  5.610544  4.688639  6.426793  6.399879
Cliente B  3.862963  3.882321  6.509361  7.290697  6.879663
Cliente C  4.289086  5.004976  5.917315  6.063510  4.351254
Cliente D  5.305981  5.015416  2.568842  6.364133  6.913206

Promedio por cliente:
Cliente A    5.316690
Cliente B    5.685001
Cliente C    5.125228
Cliente D    5.233516
dtype: float64

Promedio por mes:
Enero      4.228907
Febrero    4.878314
Marzo      4.921039
Abril      6.536283
Mayo       6.136000
dtype: float64


## 6.1. Temperaturas por ciudades

Aplicación: simulación de datos en formato matricial y análisis por filas y columnas.


In [ ]:
np.random.seed(100)
datos = np.random.uniform(15, 35, size=20)
matriz = datos.reshape(4, 5)

filas = ['Bogotá', 'Medellín', 'Cali', 'Barranquilla']
columnas = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes']

df_matriz_1 = pd.DataFrame(matriz, index=filas, columns=columnas)
print(df_matriz_1)
print('\nEstadísticos por columnas:')
print(df_matriz_1.describe())
print('\nPromedio por fila:')
print(df_matriz_1.mean(axis=1))
print('\nMáximo por columna:')
print(df_matriz_1.max(axis=0))
print('\nFormato largo usando melt:')
df_matriz_1_largo = df_matriz_1.reset_index().melt(id_vars='index', var_name='Día', value_name='Valor')
df_matriz_1_largo = df_matriz_1_largo.rename(columns={'index': 'Ciudad'})
print(df_matriz_1_largo.head())

                  Lunes     Martes  Miércoles     Jueves    Viernes
Bogotá        25.868099  20.567388  23.490352  31.895523  15.094377
Medellín      17.431382  28.414982  31.517055  17.734132  26.501867
Cali          32.826439  19.184042  18.706564  17.167538  19.393950
Barranquilla  34.572476  31.233663  18.438820  31.324495  20.481475

Estadísticos por columnas:
           Lunes     Martes  Miércoles     Jueves    Viernes
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean   27.674599  24.850019  23.038198  24.530422  20.367917
std     7.795492   5.885125   6.110450   8.181397   4.704504
min    17.431382  19.184042  18.438820  17.167538  15.094377
25%    23.758920  20.221551  18.639628  17.592483  18.319057
50%    29.347269  24.491185  21.098458  24.529313  19.937712
75%    33.262948  29.119652  25.497028  31.467252  21.986573
max    34.572476  31.233663  31.517055  31.895523  26.501867

Promedio por fila:
Bogotá          23.383148
Medellín        24.319884
Cali       

## 6.2. Ventas de productos tecnológicos

Aplicación: simulación de datos en formato matricial y análisis por filas y columnas.


In [ ]:
np.random.seed(200)
datos = np.random.uniform(1000, 5000, size=20)
matriz = datos.reshape(4, 5)

filas = ['Laptop', 'Tablet', 'Monitor', 'Celular']
columnas = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo']

df_matriz_2 = pd.DataFrame(matriz, index=filas, columns=columnas)
print(df_matriz_2)
print('\nEstadísticos por columnas:')
print(df_matriz_2.describe())
print('\nPromedio por fila:')
print(df_matriz_2.mean(axis=1))
print('\nMáximo por columna:')
print(df_matriz_2.max(axis=0))
print('\nFormato largo usando melt:')
df_matriz_2_largo = df_matriz_2.reset_index().melt(id_vars='index', var_name='Mes', value_name='Valor')
df_matriz_2_largo = df_matriz_2_largo.rename(columns={'index': 'Producto'})
print(df_matriz_2_largo.head())

               Enero      Febrero        Marzo        Abril         Mayo
Laptop   4790.529027  1906.189685  3377.680578  2713.234740  4056.562746
Tablet   1011.442367  2429.694725  4638.779543  2824.323942  4927.210837
Monitor  4469.427962  4944.110046  4693.066827  2214.773256  4384.413961
Celular  1484.887874  4142.305142  2002.020219  1384.118841  4773.964148

Estadísticos por columnas:
             Enero      Febrero        Marzo        Abril         Mayo
count     4.000000     4.000000     4.000000     4.000000     4.000000
mean   2939.071807  3355.574899  3677.886791  2284.112695  4535.537923
std    1966.408738  1425.992050  1271.817325   655.939737   392.645051
min    1011.442367  1906.189685  2002.020219  1384.118841  4056.562746
25%    1366.526497  2298.818465  3033.765488  2007.109652  4302.451158
50%    2977.157918  3285.999934  4008.230060  2464.003998  4579.189055
75%    4549.703228  4342.756368  4652.351364  2741.007040  4812.275820
max    4790.529027  4944.110046  4693.0

## 6.3. Rendimiento académico

Aplicación: simulación de datos en formato matricial y análisis por filas y columnas.


In [ ]:
np.random.seed(300)
datos = np.random.uniform(2.0, 5.0, size=20)
matriz = datos.reshape(4, 5)

filas = ['Ana', 'Carlos', 'Luisa', 'Pedro']
columnas = ['Matemáticas', 'Estadística', 'Python', 'Economía', 'IA']

df_matriz_3 = pd.DataFrame(matriz, index=filas, columns=columnas)
print(df_matriz_3)
print('\nEstadísticos por columnas:')
print(df_matriz_3.describe())
print('\nPromedio por fila:')
print(df_matriz_3.mean(axis=1))
print('\nMáximo por columna:')
print(df_matriz_3.max(axis=0))
print('\nFormato largo usando melt:')
df_matriz_3_largo = df_matriz_3.reset_index().melt(id_vars='index', var_name='Materia', value_name='Valor')
df_matriz_3_largo = df_matriz_3_largo.rename(columns={'index': 'Estudiante'})
print(df_matriz_3_largo.head())

        Matemáticas  Estadística    Python  Economía        IA
Ana        3.353368     2.663067  3.107244  2.872327  2.723234
Carlos     4.346139     4.433283  3.202372  2.077998  3.828119
Luisa      3.887264     3.955763  4.575773  3.760408  4.112505
Pedro      3.457705     4.053249  2.337105  2.547174  4.091144

Estadísticos por columnas:
       Matemáticas  Estadística    Python  Economía        IA
count     4.000000     4.000000  4.000000  4.000000  4.000000
mean      3.761119     3.776340  3.305623  2.814477  3.688751
std       0.453315     0.770243  0.931186  0.709926  0.656540
min       3.353368     2.663067  2.337105  2.077998  2.723234
25%       3.431621     3.632589  2.914709  2.429880  3.551898
50%       3.672485     4.004506  3.154808  2.709751  3.959632
75%       4.001983     4.148258  3.545722  3.094347  4.096485
max       4.346139     4.433283  4.575773  3.760408  4.112505

Promedio por fila:
Ana       2.943848
Carlos    3.577582
Luisa     4.058343
Pedro     3.297275
dty

## 6.4. Sensores de fábrica

Aplicación: simulación de datos en formato matricial y análisis por filas y columnas.


In [ ]:
np.random.seed(400)
datos = np.random.uniform(30, 100, size=20)
matriz = datos.reshape(4, 5)

filas = ['Sensor 1', 'Sensor 2', 'Sensor 3', 'Sensor 4']
columnas = ['08:00', '10:00', '12:00', '14:00', '16:00']

df_matriz_4 = pd.DataFrame(matriz, index=filas, columns=columnas)
print(df_matriz_4)
print('\nEstadísticos por columnas:')
print(df_matriz_4.describe())
print('\nPromedio por fila:')
print(df_matriz_4.mean(axis=1))
print('\nMáximo por columna:')
print(df_matriz_4.max(axis=0))
print('\nFormato largo usando melt:')
df_matriz_4_largo = df_matriz_4.reset_index().melt(id_vars='index', var_name='Hora', value_name='Valor')
df_matriz_4_largo = df_matriz_4_largo.rename(columns={'index': 'Sensor'})
print(df_matriz_4_largo.head())

              08:00      10:00      12:00      14:00      16:00
Sensor 1  76.811024  45.819893  90.150912  50.327575  40.375108
Sensor 2  30.843387  84.330787  58.331529  89.917229  67.714985
Sensor 3  65.678271  56.302916  42.046200  40.694300  94.689684
Sensor 4  32.479711  89.266590  74.654997  64.956223  97.865901

Estadísticos por columnas:


           08:00      10:00      12:00      14:00      16:00
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean   51.453098  68.930046  66.295909  61.473831  75.161420
std    23.310438  21.168226  20.739779  21.425700  26.847616
min    30.843387  45.819893  42.046200  40.694300  40.375108
25%    32.070630  53.682160  54.260197  47.919256  60.880016
50%    49.078991  70.316851  66.493263  57.641899  81.202335
75%    68.461459  85.564737  78.528976  71.196474  95.483739
max    76.811024  89.266590  90.150912  89.917229  97.865901

Promedio por fila:
Sensor 1    60.696902
Sensor 2    66.227583
Sensor 3    59.882274
Sensor 4    71.844684
dtype: float64

Máximo por columna:
08:00    76.811024
10:00    89.266590
12:00    90.150912
14:00    89.917229
16:00    97.865901
dtype: float64

Formato largo usando melt:
     Sensor   Hora      Valor
0  Sensor 1  08:00  76.811024
1  Sensor 2  08:00  30.843387
2  Sensor 3  08:00  65.678271
3  Sensor 4  08:00  32.479711
4  Sensor 1  10:00 

## 6.5. Indicadores financieros

Aplicación: simulación de datos en formato matricial y análisis por filas y columnas.


In [ ]:
np.random.seed(500)
datos = np.random.uniform(20000, 80000, size=20)
matriz = datos.reshape(4, 5)

filas = ['Empresa A', 'Empresa B', 'Empresa C', 'Empresa D']
columnas = ['T1', 'T2', 'T3', 'T4', 'T5']

df_matriz_5 = pd.DataFrame(matriz, index=filas, columns=columnas)
print(df_matriz_5)
print('\nEstadísticos por columnas:')
print(df_matriz_5.describe())
print('\nPromedio por fila:')
print(df_matriz_5.mean(axis=1))
print('\nMáximo por columna:')
print(df_matriz_5.max(axis=0))
print('\nFormato largo usando melt:')
df_matriz_5_largo = df_matriz_5.reset_index().melt(id_vars='index', var_name='Trimestre', value_name='Valor')
df_matriz_5_largo = df_matriz_5_largo.rename(columns={'index': 'Empresa'})
print(df_matriz_5_largo.head())

                     T1            T2            T3            T4            T5
Empresa A  61620.771620  23703.019554  59996.695837  53552.536210  25106.637375
Empresa B  43545.143400  49824.651643  39928.944476  40540.307145  41938.209844
Empresa C  71037.547010  46909.846617  38988.322224  41703.990127  47043.345703
Empresa D  74916.083848  47597.514868  36420.767484  75049.767018  47571.933352

Estadísticos por columnas:
                 T1            T2            T3            T4            T5
count      4.000000      4.000000      4.000000      4.000000      4.000000
mean   62779.886470  42008.758170  43833.682505  52711.650125  40415.031569
std    13985.648985  12267.071458  10876.868489  16010.504097  10517.014726
min    43545.143400  23703.019554  36420.767484  40540.307145  25106.637375
25%    57101.864565  41108.139851  38346.433539  41413.069381  37730.316727
50%    66329.159315  47253.680742  39458.633350  47628.263168  44490.777774
75%    72007.181219  48154.299062  44945

# 7. Paneles 3D con NumPy

Un panel 3D puede entenderse como un cubo de datos con tres ejes. En la práctica, puede representar `Clientes × Meses × Variables`, `Tiendas × Días × Productos` o `Regiones × Años × Indicadores`.


In [ ]:
# Ejemplo base: Panel de ingresos

np.random.seed(234)
panel = np.random.uniform(2000, 7000, size=(3, 4, 2))

print('Array 3D (Panel de ingresos):')
print(panel)
print('\nDimensiones del panel:')
print(panel.shape)

Array 3D (Panel de ingresos):
[[[2154.83671735 3271.41036617]
  [6562.00221753 6850.87098904]
  [3233.09887944 5494.03707139]
  [6332.14659598 5197.60923555]]

 [[4284.21824192 4493.97375957]
  [5602.37503466 3356.26594844]
  [6003.0951571  4546.26337518]
  [6099.60510325 3538.56618612]]

 [[5296.39110649 3567.54445378]
  [4723.25954763 3599.20730906]
  [4295.76393584 6065.45807593]
  [6787.75830755 2019.96751609]]]

Dimensiones del panel:
(3, 4, 2)


## 7.1. Array 3D: Ventas de tiendas por trimestre

Aplicación: representación de información con tres dimensiones: entidad, tiempo/posición y variables medidas.


In [ ]:
np.random.seed(100)
panel_1 = np.random.uniform(5000, 20000, size=(3, 4, 2))
print(panel_1)
print('\nDimensiones:')
print(panel_1.shape)
print('\nPromedio global:')
print(panel_1.mean())
print('\nPromedio por entidad del eje 1:')
print(panel_1.mean(axis=(1, 2)))
print('\nPromedio por variable del eje 3:')
print(panel_1.mean(axis=(0, 1)))

[[[13151.07412686  9175.54077641]
  [11367.76386124 17671.6419848 ]
  [ 5070.78284286  6823.53681175]
  [15061.2362709  17387.79132658]]

 [[ 7050.59884527 13626.39994141]
  [18369.82931468  8138.03183176]
  [ 7779.92329325  6625.65335696]
  [ 8295.46238937 19679.35677061]]

 [[17175.24723634  7579.11519099]
  [17243.37123089  9111.10620563]
  [11475.56275495 19100.44729434]
  [17264.74068165 10041.67925181]]]

Dimensiones:
(3, 4, 2)

Promedio global:
12261.078899637898

Promedio por entidad del eje 1:
[11963.67100017 11195.65696792 13623.90873082]

Promedio por variable del eje 3:
[12442.13273736 12080.02506192]


## 7.2. Array 3D: Hospitales y variables médicas

Aplicación: representación de información con tres dimensiones: entidad, tiempo/posición y variables medidas.


In [ ]:
np.random.seed(200)
panel_2 = np.random.uniform(60, 180, size=(3, 4, 2))
print(panel_2)
print('\nDimensiones:')
print(panel_2.shape)
print('\nPromedio global:')
print(panel_2.mean())
print('\nPromedio por entidad del eje 1:')
print(panel_2.mean(axis=(1, 2)))
print('\nPromedio por variable del eje 3:')
print(panel_2.mean(axis=(0, 1)))

[[[173.71587082  87.18569054]
  [131.33041733 111.39704219]
  [151.69688239  60.343271  ]
  [102.89084175 169.16338628]]

 [[114.72971825 177.8163251 ]
  [164.08283886 178.32330137]
  [170.7920048   96.44319768]
  [161.53241884  74.54663621]]

 [[154.26915426  90.06060657]
  [ 71.52356522 173.21892444]
  [159.12601766 122.19901605]
  [164.82005038 129.40508281]]]

Dimensiones:
(3, 4, 2)

Promedio global:
132.94217753308428

Promedio por entidad del eje 1:
[123.46542529 142.28330514 133.07780217]

Promedio por variable del eje 3:
[143.37581505 122.50854002]


## 7.3. Array 3D: Temperaturas ambientales

Aplicación: representación de información con tres dimensiones: entidad, tiempo/posición y variables medidas.


In [ ]:
np.random.seed(300)
panel_3 = np.random.uniform(10, 40, size=(3, 4, 2))
print(panel_3)
print('\nDimensiones:')
print(panel_3.shape)
print('\nPromedio global:')
print(panel_3.mean())
print('\nPromedio por entidad del eje 1:')
print(panel_3.mean(axis=(1, 2)))
print('\nPromedio por variable del eje 3:')
print(panel_3.mean(axis=(0, 1)))

[[[23.53367706 16.63067025]
  [21.07243758 18.72327111]
  [17.23233783 33.46139299]
  [34.33283098 22.02371622]]

 [[10.77997608 28.28119144]
  [28.87264295 29.55762629]
  [35.75773312 27.60408241]
  [31.12505043 24.57705026]]

 [[30.53249031 13.37104702]
  [15.47173906 30.91144388]
  [21.05058275 22.81891744]
  [21.99453487 29.46136353]]]

Dimensiones:
(3, 4, 2)

Promedio global:
24.549075245060454

Promedio por entidad del eje 1:
[23.37629175 27.06941912 23.20151486]

Promedio por variable del eje 3:
[24.31300275 24.78514774]


## 7.4. Array 3D: Sensores IoT

Aplicación: representación de información con tres dimensiones: entidad, tiempo/posición y variables medidas.


In [ ]:
np.random.seed(400)
panel_4 = np.random.uniform(20, 100, size=(3, 4, 2))
print(panel_4)
print('\nDimensiones:')
print(panel_4.shape)
print('\nPromedio global:')
print(panel_4.mean())
print('\nPromedio por entidad del eje 1:')
print(panel_4.mean(axis=(1, 2)))
print('\nPromedio por variable del eje 3:')
print(panel_4.mean(axis=(0, 1)))

[[[73.49831271 38.07987761]
  [88.74389931 43.231514  ]
  [31.85726633 20.96387102]
  [82.09232743 52.37889029]]

 [[88.47683268 63.10284014]
  [60.7751669  50.06047557]
  [33.7670853  32.22205678]
  [93.93106788 22.83395575]]

 [[87.73324601 71.03428256]
  [59.94996886 97.56102958]
  [72.45937877 75.13679248]
  [77.9093346  54.44976598]]]

Dimensiones:
(3, 4, 2)

Promedio global:
61.34371827171905

Promedio por entidad del eje 1:
[53.85574484 55.64618512 74.52922485]

Promedio por variable del eje 3:
[70.9328239  51.75461265]


## 7.5. Array 3D: Rendimiento académico

Aplicación: representación de información con tres dimensiones: entidad, tiempo/posición y variables medidas.


In [ ]:
np.random.seed(500)
panel_5 = np.random.uniform(2, 5, size=(3, 4, 2))
print(panel_5)
print('\nDimensiones:')
print(panel_5.shape)
print('\nPromedio global:')
print(panel_5.mean())
print('\nPromedio por entidad del eje 1:')
print(panel_5.mean(axis=(1, 2)))
print('\nPromedio por variable del eje 3:')
print(panel_5.mean(axis=(0, 1)))

[[[4.08103858 2.18515098]
  [3.99983479 3.67762681]
  [2.25533187 3.17725717]
  [3.49123258 2.99644722]]

 [[3.02701536 3.09691049]
  [4.55187735 3.34549233]
  [2.94941611 3.08519951]
  [3.35216729 4.74580419]]

 [[3.37987574 2.82103837]
  [4.75248835 3.37859667]
  [3.63377363 4.07207112]
  [4.49251423 3.90772793]]]

Dimensiones:
(3, 4, 2)

Promedio global:
3.518995361535367

Promedio por entidad del eje 1:
[3.23299    3.51923533 3.80476076]

Promedio por variable del eje 3:
[3.66388049 3.37411023]


## 7.6. Array 3D: Producción agrícola

Aplicación: representación de información con tres dimensiones: entidad, tiempo/posición y variables medidas.


In [ ]:
np.random.seed(600)
panel_6 = np.random.uniform(100, 1000, size=(3, 4, 2))
print(panel_6)
print('\nDimensiones:')
print(panel_6.shape)
print('\nPromedio global:')
print(panel_6.mean())
print('\nPromedio por entidad del eje 1:')
print(panel_6.mean(axis=(1, 2)))
print('\nPromedio por variable del eje 3:')
print(panel_6.mean(axis=(0, 1)))

[[[129.13054766 588.16869676]
  [822.62764858 149.64346312]
  [444.03829764 289.87353295]
  [867.11629525 206.71418996]]

 [[111.35625652 206.3362401 ]
  [346.86033403 909.57507452]
  [305.31839263 990.18310567]
  [173.58051053 370.69702377]]

 [[929.27350518 988.66884895]
  [146.07750301 193.14751481]
  [780.31953319 413.7742936 ]
  [969.59108018 695.95025048]]]

Dimensiones:
(3, 4, 2)

Promedio global:
501.16758912927725

Promedio por entidad del eje 1:
[437.16408399 426.73836722 639.60031617]

Promedio por variable del eje 3:
[502.10749203 500.22768623]


## 7.7. Array 3D: Redes sociales

Aplicación: representación de información con tres dimensiones: entidad, tiempo/posición y variables medidas.


In [ ]:
np.random.seed(700)
panel_7 = np.random.uniform(1000, 10000, size=(3, 4, 2))
print(panel_7)
print('\nDimensiones:')
print(panel_7.shape)
print('\nPromedio global:')
print(panel_7.mean())
print('\nPromedio por entidad del eje 1:')
print(panel_7.mean(axis=(1, 2)))
print('\nPromedio por variable del eje 3:')
print(panel_7.mean(axis=(0, 1)))

[[[2408.91728169 4751.82860107]
  [1601.26203917 8788.65752785]
  [3720.63390205 7671.30275129]
  [4693.73736455 4106.22251199]]

 [[9733.4762536  8672.88933584]
  [6181.1659731  7707.73129122]
  [7166.21097429 4370.7532883 ]
  [2661.70322931 3546.11643537]]

 [[7846.98032482 6501.49674808]
  [5926.52261534 7397.22294487]
  [6272.21052802 9743.65716383]
  [9511.21601534 5649.99850049]]]

Dimensiones:
(3, 4, 2)

Promedio global:
6109.663066727349

Promedio por entidad del eje 1:
[4717.82024746 6255.00584763 7356.1631051 ]

Promedio por variable del eje 3:
[5643.66970844 6575.65642502]


## 7.8. Array 3D: Transporte urbano

Aplicación: representación de información con tres dimensiones: entidad, tiempo/posición y variables medidas.


In [ ]:
np.random.seed(800)
panel_8 = np.random.uniform(50, 500, size=(3, 4, 2))
print(panel_8)
print('\nDimensiones:')
print(panel_8.shape)
print('\nPromedio global:')
print(panel_8.mean())
print('\nPromedio por entidad del eje 1:')
print(panel_8.mean(axis=(1, 2)))
print('\nPromedio por variable del eje 3:')
print(panel_8.mean(axis=(0, 1)))

[[[ 86.62044888 222.78127575]
  [208.86245507 122.11026638]
  [178.89524721 403.70018466]
  [272.42188378 261.71822435]]

 [[468.60175368 383.52100464]
  [317.76508237  85.74224922]
  [ 99.76157709 373.62856816]
  [331.26756027 459.22163111]]

 [[149.7604654  295.16171799]
  [468.66826458 401.87424866]
  [349.05837472 149.19982518]
  [180.32188585  76.98445308]]]

Dimensiones:
(3, 4, 2)

Promedio global:
264.48536033682797

Promedio por entidad del eje 1:
[219.63874826 314.93867832 258.87865443]

Promedio por variable del eje 3:
[259.33374991 269.63697077]


## 7.9. Array 3D: Indicadores económicos

Aplicación: representación de información con tres dimensiones: entidad, tiempo/posición y variables medidas.


In [ ]:
np.random.seed(900)
panel_9 = np.random.uniform(1, 10, size=(3, 4, 2))
print(panel_9)
print('\nDimensiones:')
print(panel_9.shape)
print('\nPromedio global:')
print(panel_9.mean())
print('\nPromedio por entidad del eje 1:')
print(panel_9.mean(axis=(1, 2)))
print('\nPromedio por variable del eje 3:')
print(panel_9.mean(axis=(0, 1)))

[[[4.89881376 3.76595134]
  [5.89976607 2.3489196 ]
  [3.77604997 6.47807181]
  [3.45286392 1.62582014]]

 [[3.2272186  2.89934043]
  [6.64868066 7.54543203]
  [4.51005423 4.82317869]
  [2.19775964 3.89528582]]

 [[9.2741224  1.15274417]
  [8.31591917 8.82166038]
  [7.83028125 2.5680478 ]
  [8.00956161 3.5077542 ]]]

Dimensiones:
(3, 4, 2)

Promedio global:
4.894720738064286

Promedio por entidad del eje 1:
[4.03078208 4.46836876 6.18501137]

Promedio por variable del eje 3:
[5.67009094 4.11935053]


## 7.10. Array 3D: Deep Learning y visión artificial

Aplicación: representación de información con tres dimensiones: entidad, tiempo/posición y variables medidas.


In [ ]:
np.random.seed(1000)
panel_10 = np.random.uniform(0, 255, size=(3, 4, 2))
print(panel_10)
print('\nDimensiones:')
print(panel_10.shape)
print('\nPromedio global:')
print(panel_10.mean())
print('\nPromedio por entidad del eje 1:')
print(panel_10.mean(axis=(1, 2)))
print('\nPromedio por variable del eje 3:')
print(panel_10.mean(axis=(0, 1)))

[[[166.66534429  29.3267705 ]
  [242.32213041 122.95880736]
  [222.48100647  54.14483364]
  [ 10.38095432 101.28458764]]

 [[ 59.44871032 214.64388468]
  [ 52.80599782 189.32973106]
  [ 99.99930259  46.47541259]
  [189.60255072  17.74343065]]

 [[225.76098712 242.9243218 ]
  [237.44157584 105.93489303]
  [  7.39032314 250.41700857]
  [ 86.60760933 180.20523444]]]

Dimensiones:
(3, 4, 2)

Promedio global:
131.51230868082965

Promedio por entidad del eje 1:
[118.69555433 108.75612755 167.08524416]

Promedio por variable del eje 3:
[133.40887436 129.615743  ]


# 8. Paneles convertidos a DataFrame con MultiIndex

Pandas ya no utiliza la antigua estructura `Panel`, pero permite representar datos de panel mediante `DataFrame` con `MultiIndex`. Esta forma es muy poderosa porque facilita agrupaciones, filtros, estadísticas y transformaciones.


In [ ]:
# Ejemplo base: Panel convertido a tabla MultiIndex

clientes = ['Cliente A', 'Cliente B', 'Cliente C']
meses = ['Enero', 'Febrero', 'Marzo', 'Abril']
variables = ['Ingreso Bruto', 'Ingreso Neto']

panel_df_base = pd.DataFrame(
    panel.reshape(12, 2),
    index=pd.MultiIndex.from_product([clientes, meses], names=['Cliente', 'Mes']),
    columns=variables
)

print(panel_df_base)
print('\nPromedio por cliente:')
print(panel_df_base.groupby(level='Cliente').mean())
print('\nPromedio por mes:')
print(panel_df_base.groupby(level='Mes').mean())
print('\nTabla plana:')
print(panel_df_base.reset_index().head())

                   Ingreso Bruto  Ingreso Neto
Cliente   Mes                                 
Cliente A Enero      2154.836717   3271.410366
          Febrero    6562.002218   6850.870989
          Marzo      3233.098879   5494.037071
          Abril      6332.146596   5197.609236
Cliente B Enero      4284.218242   4493.973760
          Febrero    5602.375035   3356.265948
          Marzo      6003.095157   4546.263375
          Abril      6099.605103   3538.566186
Cliente C Enero      5296.391106   3567.544454
          Febrero    4723.259548   3599.207309
          Marzo      4295.763936   6065.458076
          Abril      6787.758308   2019.967516

Promedio por cliente:
           Ingreso Bruto  Ingreso Neto
Cliente                               
Cliente A    4570.521103   5203.481916
Cliente B    5497.323384   3983.767317
Cliente C    5275.793224   3813.044339

Promedio por mes:
         Ingreso Bruto  Ingreso Neto
Mes                                 
Abril      6406.503336   3585.3

## 8.1. MultiIndex: Ventas de tiendas por trimestre

Aplicación: conversión de un array 3D a una tabla analítica con índice jerárquico. Se pueden calcular promedios por entidad, por periodo y por variable.


In [ ]:
np.random.seed(100)
panel_temp = np.random.uniform(5000, 20000, size=(3, 4, 2))
tiendas = ['Tienda A', 'Tienda B', 'Tienda C']
trimestres = ['T1', 'T2', 'T3', 'T4']
variables = ['Ventas', 'Ganancias']

panel_df_1 = pd.DataFrame(
    panel_temp.reshape(12, 2),
    index=pd.MultiIndex.from_product([tiendas, trimestres], names=['Tiendas', 'Trimestres']),
    columns=variables
)

print(panel_df_1)
print('\nEstadísticos descriptivos:')
print(panel_df_1.describe())
print('\nPromedio por Tiendas:')
print(panel_df_1.groupby(level='Tiendas').mean())
print('\nPromedio por Trimestres:')
print(panel_df_1.groupby(level='Trimestres').mean())
print('\nConversión a tabla plana:')
panel_df_1_plano = panel_df_1.reset_index()
print(panel_df_1_plano.head())
print('\nFormato largo para visualización o modelos:')
panel_df_1_largo = panel_df_1_plano.melt(id_vars=['Tiendas', 'Trimestres'], var_name='Variable', value_name='Valor')
print(panel_df_1_largo.head())

                           Ventas     Ganancias
Tiendas  Trimestres                            
Tienda A T1          13151.074127   9175.540776
         T2          11367.763861  17671.641985
         T3           5070.782843   6823.536812
         T4          15061.236271  17387.791327
Tienda B T1           7050.598845  13626.399941
         T2          18369.829315   8138.031832
         T3           7779.923293   6625.653357
         T4           8295.462389  19679.356771
Tienda C T1          17175.247236   7579.115191
         T2          17243.371231   9111.106206
         T3          11475.562755  19100.447294
         T4          17264.740682  10041.679252

Estadísticos descriptivos:
             Ventas     Ganancias
count     12.000000     12.000000
mean   12442.132737  12080.025062
std     4628.338933   5076.234378
min     5070.782843   6625.653357
25%     8166.577615   7998.302672
50%    12313.318441   9608.610014
75%    17192.278235  17458.753991
max    18369.829315  19679.3

## 8.2. MultiIndex: Hospitales y variables médicas

Aplicación: conversión de un array 3D a una tabla analítica con índice jerárquico. Se pueden calcular promedios por entidad, por periodo y por variable.


In [ ]:
np.random.seed(200)
panel_temp = np.random.uniform(60, 180, size=(3, 4, 2))
hospitales = ['Hospital A', 'Hospital B', 'Hospital C']
semanas = ['Semana 1', 'Semana 2', 'Semana 3', 'Semana 4']
variables = ['Presión', 'Glucosa']

panel_df_2 = pd.DataFrame(
    panel_temp.reshape(12, 2),
    index=pd.MultiIndex.from_product([hospitales, semanas], names=['Hospitales', 'Semanas']),
    columns=variables
)

print(panel_df_2)
print('\nEstadísticos descriptivos:')
print(panel_df_2.describe())
print('\nPromedio por Hospitales:')
print(panel_df_2.groupby(level='Hospitales').mean())
print('\nPromedio por Semanas:')
print(panel_df_2.groupby(level='Semanas').mean())
print('\nConversión a tabla plana:')
panel_df_2_plano = panel_df_2.reset_index()
print(panel_df_2_plano.head())
print('\nFormato largo para visualización o modelos:')
panel_df_2_largo = panel_df_2_plano.melt(id_vars=['Hospitales', 'Semanas'], var_name='Variable', value_name='Valor')
print(panel_df_2_largo.head())

                        Presión     Glucosa
Hospitales Semanas                         
Hospital A Semana 1  173.715871   87.185691
           Semana 2  131.330417  111.397042
           Semana 3  151.696882   60.343271
           Semana 4  102.890842  169.163386
Hospital B Semana 1  114.729718  177.816325
           Semana 2  164.082839  178.323301
           Semana 3  170.792005   96.443198
           Semana 4  161.532419   74.546636
Hospital C Semana 1  154.269154   90.060607
           Semana 2   71.523565  173.218924
           Semana 3  159.126018  122.199016
           Semana 4  164.820050  129.405083

Estadísticos descriptivos:
          Presión     Glucosa
count   12.000000   12.000000
mean   143.375815  122.508540
std     31.757473   42.893546
min     71.523565   60.343271
25%    127.180243   89.341878
50%    156.697586  116.798029
75%    164.267142  170.177271
max    173.715871  178.323301

Promedio por Hospitales:
               Presión     Glucosa
Hospitales               

## 8.3. MultiIndex: Temperaturas ambientales

Aplicación: conversión de un array 3D a una tabla analítica con índice jerárquico. Se pueden calcular promedios por entidad, por periodo y por variable.


In [ ]:
np.random.seed(300)
panel_temp = np.random.uniform(10, 40, size=(3, 4, 2))
ciudades = ['Bogotá', 'Cali', 'Medellín']
meses = ['Enero', 'Febrero', 'Marzo', 'Abril']
variables = ['Temp Max', 'Temp Min']

panel_df_3 = pd.DataFrame(
    panel_temp.reshape(12, 2),
    index=pd.MultiIndex.from_product([ciudades, meses], names=['Ciudades', 'Meses']),
    columns=variables
)

print(panel_df_3)
print('\nEstadísticos descriptivos:')
print(panel_df_3.describe())
print('\nPromedio por Ciudades:')
print(panel_df_3.groupby(level='Ciudades').mean())
print('\nPromedio por Meses:')
print(panel_df_3.groupby(level='Meses').mean())
print('\nConversión a tabla plana:')
panel_df_3_plano = panel_df_3.reset_index()
print(panel_df_3_plano.head())
print('\nFormato largo para visualización o modelos:')
panel_df_3_largo = panel_df_3_plano.melt(id_vars=['Ciudades', 'Meses'], var_name='Variable', value_name='Valor')
print(panel_df_3_largo.head())

                   Temp Max   Temp Min
Ciudades Meses                        
Bogotá   Enero    23.533677  16.630670
         Febrero  21.072438  18.723271
         Marzo    17.232338  33.461393
         Abril    34.332831  22.023716
Cali     Enero    10.779976  28.281191
         Febrero  28.872643  29.557626
         Marzo    35.757733  27.604082
         Abril    31.125050  24.577050
Medellín Enero    30.532490  13.371047
         Febrero  15.471739  30.911444
         Marzo    21.050583  22.818917
         Abril    21.994535  29.461364

Estadísticos descriptivos:
        Temp Max   Temp Min
count  12.000000  12.000000
mean   24.313003  24.785148
std     7.838303   6.198823
min    10.779976  13.371047
25%    20.096022  21.198605
50%    22.764106  26.090566
75%    30.680630  29.485429
max    35.757733  33.461393

Promedio por Ciudades:
           Temp Max   Temp Min
Ciudades                      
Bogotá    24.042821  22.709763
Cali      26.633851  27.504988
Medellín  22.262337  24.14

## 8.4. MultiIndex: Sensores IoT

Aplicación: conversión de un array 3D a una tabla analítica con índice jerárquico. Se pueden calcular promedios por entidad, por periodo y por variable.


In [ ]:
np.random.seed(400)
panel_temp = np.random.uniform(20, 100, size=(3, 4, 2))
sensores = ['Sensor 1', 'Sensor 2', 'Sensor 3']
horas = ['08:00', '10:00', '12:00', '14:00']
variables = ['Temperatura', 'Humedad']

panel_df_4 = pd.DataFrame(
    panel_temp.reshape(12, 2),
    index=pd.MultiIndex.from_product([sensores, horas], names=['Sensores', 'Horas']),
    columns=variables
)

print(panel_df_4)
print('\nEstadísticos descriptivos:')
print(panel_df_4.describe())
print('\nPromedio por Sensores:')
print(panel_df_4.groupby(level='Sensores').mean())
print('\nPromedio por Horas:')
print(panel_df_4.groupby(level='Horas').mean())
print('\nConversión a tabla plana:')
panel_df_4_plano = panel_df_4.reset_index()
print(panel_df_4_plano.head())
print('\nFormato largo para visualización o modelos:')
panel_df_4_largo = panel_df_4_plano.melt(id_vars=['Sensores', 'Horas'], var_name='Variable', value_name='Valor')
print(panel_df_4_largo.head())

                Temperatura    Humedad
Sensores Horas                        
Sensor 1 08:00    73.498313  38.079878
         10:00    88.743899  43.231514
         12:00    31.857266  20.963871
         14:00    82.092327  52.378890
Sensor 2 08:00    88.476833  63.102840
         10:00    60.775167  50.060476
         12:00    33.767085  32.222057
         14:00    93.931068  22.833956
Sensor 3 08:00    87.733246  71.034283
         10:00    59.949969  97.561030
         12:00    72.459379  75.136792
         14:00    77.909335  54.449766

Estadísticos descriptivos:
       Temperatura    Humedad
count    12.000000  12.000000
mean     70.932824  51.754613
std      20.780915  22.525949
min      31.857266  20.963871
25%      60.568867  36.615422
50%      75.703824  51.219683
75%      87.919143  65.085701
max      93.931068  97.561030

Promedio por Sensores:
          Temperatura    Humedad
Sensores                        
Sensor 1    69.047951  38.663538
Sensor 2    69.237538  42.054832


## 8.5. MultiIndex: Rendimiento académico

Aplicación: conversión de un array 3D a una tabla analítica con índice jerárquico. Se pueden calcular promedios por entidad, por periodo y por variable.


In [ ]:
np.random.seed(500)
panel_temp = np.random.uniform(2, 5, size=(3, 4, 2))
estudiantes = ['Ana', 'Pedro', 'Luisa']
semestres = ['2023-1', '2023-2', '2024-1', '2024-2']
variables = ['Parcial', 'Final']

panel_df_5 = pd.DataFrame(
    panel_temp.reshape(12, 2),
    index=pd.MultiIndex.from_product([estudiantes, semestres], names=['Estudiantes', 'Semestres']),
    columns=variables
)

print(panel_df_5)
print('\nEstadísticos descriptivos:')
print(panel_df_5.describe())
print('\nPromedio por Estudiantes:')
print(panel_df_5.groupby(level='Estudiantes').mean())
print('\nPromedio por Semestres:')
print(panel_df_5.groupby(level='Semestres').mean())
print('\nConversión a tabla plana:')
panel_df_5_plano = panel_df_5.reset_index()
print(panel_df_5_plano.head())
print('\nFormato largo para visualización o modelos:')
panel_df_5_largo = panel_df_5_plano.melt(id_vars=['Estudiantes', 'Semestres'], var_name='Variable', value_name='Valor')
print(panel_df_5_largo.head())

                        Parcial     Final
Estudiantes Semestres                    
Ana         2023-1     4.081039  2.185151
            2023-2     3.999835  3.677627
            2024-1     2.255332  3.177257
            2024-2     3.491233  2.996447
Pedro       2023-1     3.027015  3.096910
            2023-2     4.551877  3.345492
            2024-1     2.949416  3.085200
            2024-2     3.352167  4.745804
Luisa       2023-1     3.379876  2.821038
            2023-2     4.752488  3.378597
            2024-1     3.633774  4.072071
            2024-2     4.492514  3.907728

Estadísticos descriptivos:
         Parcial      Final
count  12.000000  12.000000
mean    3.663880   3.374110
std     0.741971   0.661101
min     2.255332   2.185151
25%     3.270879   3.063011
50%     3.562503   3.261375
75%     4.183907   3.735152
max     4.752488   4.745804

Promedio por Estudiantes:
              Parcial     Final
Estudiantes                    
Ana          3.456859  3.009121
Luisa    

## 8.6. MultiIndex: Producción agrícola

Aplicación: conversión de un array 3D a una tabla analítica con índice jerárquico. Se pueden calcular promedios por entidad, por periodo y por variable.


In [ ]:
np.random.seed(600)
panel_temp = np.random.uniform(100, 1000, size=(3, 4, 2))
fincas = ['Finca A', 'Finca B', 'Finca C']
meses = ['Enero', 'Febrero', 'Marzo', 'Abril']
variables = ['Producción', 'Ventas']

panel_df_6 = pd.DataFrame(
    panel_temp.reshape(12, 2),
    index=pd.MultiIndex.from_product([fincas, meses], names=['Fincas', 'Meses']),
    columns=variables
)

print(panel_df_6)
print('\nEstadísticos descriptivos:')
print(panel_df_6.describe())
print('\nPromedio por Fincas:')
print(panel_df_6.groupby(level='Fincas').mean())
print('\nPromedio por Meses:')
print(panel_df_6.groupby(level='Meses').mean())
print('\nConversión a tabla plana:')
panel_df_6_plano = panel_df_6.reset_index()
print(panel_df_6_plano.head())
print('\nFormato largo para visualización o modelos:')
panel_df_6_largo = panel_df_6_plano.melt(id_vars=['Fincas', 'Meses'], var_name='Variable', value_name='Valor')
print(panel_df_6_largo.head())

                 Producción      Ventas
Fincas  Meses                          
Finca A Enero    129.130548  588.168697
        Febrero  822.627649  149.643463
        Marzo    444.038298  289.873533
        Abril    867.116295  206.714190
Finca B Enero    111.356257  206.336240
        Febrero  346.860334  909.575075
        Marzo    305.318393  990.183106
        Abril    173.580511  370.697024
Finca C Enero    929.273505  988.668849
        Febrero  146.077503  193.147515
        Marzo    780.319533  413.774294
        Abril    969.591080  695.950250

Estadísticos descriptivos:
       Producción      Ventas
count   12.000000   12.000000
mean   502.107492  500.227686
std    344.708515  323.400743
min    111.356257  149.643463
25%    166.704759  206.619702
50%    395.449316  392.235659
75%    833.749810  749.356456
max    969.591080  990.183106

Promedio por Fincas:
         Producción      Ventas
Fincas                         
Finca A  565.728197  308.599971
Finca B  234.278873  619

## 8.7. MultiIndex: Redes sociales

Aplicación: conversión de un array 3D a una tabla analítica con índice jerárquico. Se pueden calcular promedios por entidad, por periodo y por variable.


In [ ]:
np.random.seed(700)
panel_temp = np.random.uniform(1000, 10000, size=(3, 4, 2))
usuarios = ['User1', 'User2', 'User3']
semanas = ['Semana 1', 'Semana 2', 'Semana 3', 'Semana 4']
variables = ['Likes', 'Comentarios']

panel_df_7 = pd.DataFrame(
    panel_temp.reshape(12, 2),
    index=pd.MultiIndex.from_product([usuarios, semanas], names=['Usuarios', 'Semanas']),
    columns=variables
)

print(panel_df_7)
print('\nEstadísticos descriptivos:')
print(panel_df_7.describe())
print('\nPromedio por Usuarios:')
print(panel_df_7.groupby(level='Usuarios').mean())
print('\nPromedio por Semanas:')
print(panel_df_7.groupby(level='Semanas').mean())
print('\nConversión a tabla plana:')
panel_df_7_plano = panel_df_7.reset_index()
print(panel_df_7_plano.head())
print('\nFormato largo para visualización o modelos:')
panel_df_7_largo = panel_df_7_plano.melt(id_vars=['Usuarios', 'Semanas'], var_name='Variable', value_name='Valor')
print(panel_df_7_largo.head())

                         Likes  Comentarios
Usuarios Semanas                           
User1    Semana 1  2408.917282  4751.828601
         Semana 2  1601.262039  8788.657528
         Semana 3  3720.633902  7671.302751
         Semana 4  4693.737365  4106.222512
User2    Semana 1  9733.476254  8672.889336
         Semana 2  6181.165973  7707.731291
         Semana 3  7166.210974  4370.753288
         Semana 4  2661.703229  3546.116435
User3    Semana 1  7846.980325  6501.496748
         Semana 2  5926.522615  7397.222945
         Semana 3  6272.210528  9743.657164
         Semana 4  9511.216015  5649.998500

Estadísticos descriptivos:
             Likes  Comentarios
count    12.000000    12.000000
mean   5643.669708  6575.656425
std    2695.423030  2062.996470
min    1601.262039  3546.116435
25%    3455.901234  4656.559773
50%    6053.844294  6949.359846
75%    7336.403312  7949.020802
max    9733.476254  9743.657164

Promedio por Usuarios:
                Likes  Comentarios
Usuarios 

## 8.8. MultiIndex: Transporte urbano

Aplicación: conversión de un array 3D a una tabla analítica con índice jerárquico. Se pueden calcular promedios por entidad, por periodo y por variable.


In [ ]:
np.random.seed(800)
panel_temp = np.random.uniform(50, 500, size=(3, 4, 2))
estaciones = ['Norte', 'Centro', 'Sur']
dias = ['Lunes', 'Martes', 'Miércoles', 'Jueves']
variables = ['Entradas', 'Salidas']

panel_df_8 = pd.DataFrame(
    panel_temp.reshape(12, 2),
    index=pd.MultiIndex.from_product([estaciones, dias], names=['Estaciones', 'Dias']),
    columns=variables
)

print(panel_df_8)
print('\nEstadísticos descriptivos:')
print(panel_df_8.describe())
print('\nPromedio por Estaciones:')
print(panel_df_8.groupby(level='Estaciones').mean())
print('\nPromedio por Dias:')
print(panel_df_8.groupby(level='Dias').mean())
print('\nConversión a tabla plana:')
panel_df_8_plano = panel_df_8.reset_index()
print(panel_df_8_plano.head())
print('\nFormato largo para visualización o modelos:')
panel_df_8_largo = panel_df_8_plano.melt(id_vars=['Estaciones', 'Dias'], var_name='Variable', value_name='Valor')
print(panel_df_8_largo.head())

                        Entradas     Salidas
Estaciones Dias                             
Norte      Lunes       86.620449  222.781276
           Martes     208.862455  122.110266
           Miércoles  178.895247  403.700185
           Jueves     272.421884  261.718224
Centro     Lunes      468.601754  383.521005
           Martes     317.765082   85.742249
           Miércoles   99.761577  373.628568
           Jueves     331.267560  459.221631
Sur        Lunes      149.760465  295.161718
           Martes     468.668265  401.874249
           Miércoles  349.058375  149.199825
           Jueves     180.321886   76.984453

Estadísticos descriptivos:
         Entradas     Salidas
count   12.000000   12.000000
mean   259.333750  269.636971
std    130.378674  136.613916
min     86.620449   76.984453
25%    171.611552  142.427435
50%    240.642169  278.439971
75%    335.715264  388.109316
max    468.668265  459.221631

Promedio por Estaciones:
              Entradas     Salidas
Estaciones 

## 8.9. MultiIndex: Indicadores económicos

Aplicación: conversión de un array 3D a una tabla analítica con índice jerárquico. Se pueden calcular promedios por entidad, por periodo y por variable.


In [ ]:
np.random.seed(900)
panel_temp = np.random.uniform(1, 10, size=(3, 4, 2))
paises = ['Colombia', 'Brasil', 'México']
anios = ['2021', '2022', '2023', '2024']
variables = ['Inflación', 'Desempleo']

panel_df_9 = pd.DataFrame(
    panel_temp.reshape(12, 2),
    index=pd.MultiIndex.from_product([paises, anios], names=['Paises', 'Anios']),
    columns=variables
)

print(panel_df_9)
print('\nEstadísticos descriptivos:')
print(panel_df_9.describe())
print('\nPromedio por Paises:')
print(panel_df_9.groupby(level='Paises').mean())
print('\nPromedio por Anios:')
print(panel_df_9.groupby(level='Anios').mean())
print('\nConversión a tabla plana:')
panel_df_9_plano = panel_df_9.reset_index()
print(panel_df_9_plano.head())
print('\nFormato largo para visualización o modelos:')
panel_df_9_largo = panel_df_9_plano.melt(id_vars=['Paises', 'Anios'], var_name='Variable', value_name='Valor')
print(panel_df_9_largo.head())

                Inflación  Desempleo
Paises   Anios                      
Colombia 2021    4.898814   3.765951
         2022    5.899766   2.348920
         2023    3.776050   6.478072
         2024    3.452864   1.625820
Brasil   2021    3.227219   2.899340
         2022    6.648681   7.545432
         2023    4.510054   4.823179
         2024    2.197760   3.895286
México   2021    9.274122   1.152744
         2022    8.315919   8.821660
         2023    7.830281   2.568048
         2024    8.009562   3.507754

Estadísticos descriptivos:
       Inflación  Desempleo
count  12.000000  12.000000
mean    5.670091   4.119351
std     2.327858   2.383765
min     2.197760   1.152744
25%     3.695253   2.513266
50%     5.399290   3.636853
75%     7.875101   5.236902
max     9.274122   8.821660

Promedio por Paises:
          Inflación  Desempleo
Paises                        
Brasil     4.145928   4.790809
Colombia   4.506873   3.554691
México     8.357471   4.012552

Promedio por Anios:
    

## 8.10. MultiIndex: Deep Learning y visión artificial

Aplicación: conversión de un array 3D a una tabla analítica con índice jerárquico. Se pueden calcular promedios por entidad, por periodo y por variable.


In [ ]:
np.random.seed(1000)
panel_temp = np.random.uniform(0, 255, size=(3, 4, 2))
imagenes = ['Imagen1', 'Imagen2', 'Imagen3']
pixeles = ['Pixel1', 'Pixel2', 'Pixel3', 'Pixel4']
variables = ['Canal R', 'Canal G']

panel_df_10 = pd.DataFrame(
    panel_temp.reshape(12, 2),
    index=pd.MultiIndex.from_product([imagenes, pixeles], names=['Imagenes', 'Pixeles']),
    columns=variables
)

print(panel_df_10)
print('\nEstadísticos descriptivos:')
print(panel_df_10.describe())
print('\nPromedio por Imagenes:')
print(panel_df_10.groupby(level='Imagenes').mean())
print('\nPromedio por Pixeles:')
print(panel_df_10.groupby(level='Pixeles').mean())
print('\nConversión a tabla plana:')
panel_df_10_plano = panel_df_10.reset_index()
print(panel_df_10_plano.head())
print('\nFormato largo para visualización o modelos:')
panel_df_10_largo = panel_df_10_plano.melt(id_vars=['Imagenes', 'Pixeles'], var_name='Variable', value_name='Valor')
print(panel_df_10_largo.head())

                     Canal R     Canal G
Imagenes Pixeles                        
Imagen1  Pixel1   166.665344   29.326770
         Pixel2   242.322130  122.958807
         Pixel3   222.481006   54.144834
         Pixel4    10.380954  101.284588
Imagen2  Pixel1    59.448710  214.643885
         Pixel2    52.805998  189.329731
         Pixel3    99.999303   46.475413
         Pixel4   189.602551   17.743431
Imagen3  Pixel1   225.760987  242.924322
         Pixel2   237.441576  105.934893
         Pixel3     7.390323  250.417009
         Pixel4    86.607609  180.205234

Estadísticos descriptivos:
          Canal R     Canal G
count   12.000000   12.000000
mean   133.408874  129.615743
std     90.303232   83.869942
min      7.390323   17.743431
25%     57.788032   52.227478
50%    133.332323  114.446850
75%    223.301002  195.658269
max    242.322130  250.417009

Promedio por Imagenes:
             Canal R     Canal G
Imagenes                        
Imagen1   160.462359   76.928750
Image

# 9. Resumen final de procesos estadísticos y de manipulación

| Tipo de estructura | Procesos recomendados |
|---|---|
| `Series` | `describe()`, `mean()`, `median()`, `std()`, `sort_values()`, filtros booleanos, `idxmax()`, `idxmin()` |
| `DataFrame` | `head()`, `info()`, `dtypes`, `describe()`, selección de columnas, filtros, `groupby()`, creación de columnas |
| Variables tipo texto | `value_counts()`, `astype('string')`, limpieza con `.str`, codificación para modelos |
| Variables numéricas | `pd.to_numeric()`, media, mediana, desviación estándar, normalización, detección de valores extremos |
| Matrices 2D | Promedios por fila/columna, transposición, formato largo con `melt()` |
| Paneles 3D | Promedios por ejes con NumPy, conversión a `MultiIndex`, agrupación por niveles |
| MultiIndex | `groupby(level=...)`, `reset_index()`, `melt()`, filtros por niveles, análisis longitudinal |

## Conclusión

Las estructuras de Pandas y NumPy permiten pasar de datos simples a datos complejos. Las `Series` representan variables individuales; los `DataFrame` organizan información tabular; las matrices 2D permiten simulación y análisis estructurado; y los paneles 3D, al convertirse a `MultiIndex`, facilitan el análisis de datos longitudinales, multivariados y jerárquicos.
