<a href="https://colab.research.google.com/github/ManuelRomero2025/Programaci-nPython20254/blob/main/TiposdeDatosPrimitivosSimples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tipos de datos enteros en NumPy**

La tabla muestra los tipos de datos enteros en NumPy, según su tamaño en bits, si son con signo (negativos y positivos) o sin signo (solo positivos), y el rango de valores que pueden almacenar.



| Tipo     | Bits | Rango de valores                           |
| -------- | ---- | ------------------------------------------ |
| `int8`   | 8    | -128 a 127                                 |
| `int16`  | 16   | -32,768 a 32,767                           |
| `int32`  | 32   | -2,147,483,648 a 2,147,483,647             |
| `int64`  | 64   | -9.2×10¹⁸ a 9.2×10¹⁸                       |
| `uint8`  | 8    | 0 a 255 (sin signo)                        |
| `uint16` | 16   | 0 a 65,535 (sin signo)                     |
| `uint32` | 32   | 0 a 4,294,967,295 (sin signo)              |
| `uint64` | 64   | 0 a 18,446,744,073,709,551,615 (sin signo) |


In [8]:
import numpy as np
datos=np.array([12, 23, 46, 45])
datos.dtype

dtype('int64')

In [17]:
datosUno=np.array([12, -23, 46, 45], dtype='float64')
datosUno.dtype

dtype('float64')

In [15]:
print(datosUno)

[ 12. -23.  46.  45.]


# Listas [lista]

Mutable=se puede modificar (Agregar, eliminar, sustituir)

In [21]:
Lista=[12, 24, 26, 30, 32, 34]
np.array(Lista)

array([12, 24, 26, 30, 32, 34])

In [22]:
Lista[0]=80
Lista[3]=100
print(Lista)

[80, 24, 26, 100, 32, 34]


In [26]:
A=[1,2,3,4,5]
B=[6,7,8,9,10]
A+B

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [28]:
C=np.array([12, 24, 36, 48])
D=np.array([2,3,4,5])
C+D

array([14, 27, 40, 53])

## tuplas (tuplas)

* Inmutable: no pueden alterarse durante la ejecución de un programa.


In [29]:
tuplas=(12,14,16,18,10)
print(tuplas)

(12, 14, 16, 18, 10)


In [31]:
 #tuplas[3]=17 No se puede modificart ya que es una tupla

In [35]:
tuplaUno=np.array(tuplas)
tuplaUno[2]=20
print(tuplaUno)

[12 14 20 18 10]


In [36]:
tuplaA=[12, 13, 14, 15]
tuplaB=[2,3,4,5]
tuplaA+tuplaB

[12, 13, 14, 15, 2, 3, 4, 5]

In [41]:
np.array(tuplaA)+np.array(tuplaB)

array([14, 16, 18, 20])

In [42]:
#Tupla a lista
list((12,24,25))

[12, 24, 25]

In [43]:
#lista a Tupla
tuple([12, 13, 15, 15])

(12, 13, 15, 15)

In [44]:
#array a lista
ar1=np.array([12, 13, 15, 15])
ar1.tolist()

[12, 13, 15, 15]

# **Diccionario {dict}**




In [59]:
valorUno={"Colombia":20.56, "Perú":21.8, "Argentina": 23.5}
print(valorUno)

{'Colombia': 20.56, 'Perú': 21.8, 'Argentina': 23.5}


In [63]:
arrayDic=np.array(list(valorUno.values()))
print(arrayDic)


[20.56 21.8  23.5 ]


In [62]:
print(arrayDic*2)


[41.12 43.6  47.  ]


In [67]:
valorUno["Colombia"]

61.67999999999999

# **Operaciones Lógicas**

* False
* True


In [68]:
a=np.array([0,5,10, 30, 100])
print(a>10) #mayores

[False False False  True  True]


In [69]:
print(a>=10) #mayores que

[False False  True  True  True]


In [70]:
print(a<30) #menore

[ True  True  True False False]


In [71]:
print(a<=30) #menores que

[ True  True  True  True False]


In [74]:
print(a==100)# identicos

[False False False False  True]


In [75]:
print(a!=30) #Diferentes

[ True  True  True False  True]


In [77]:
arrayB=np.linspace(0,200, 30)
print(arrayB)

[  0.           6.89655172  13.79310345  20.68965517  27.5862069
  34.48275862  41.37931034  48.27586207  55.17241379  62.06896552
  68.96551724  75.86206897  82.75862069  89.65517241  96.55172414
 103.44827586 110.34482759 117.24137931 124.13793103 131.03448276
 137.93103448 144.82758621 151.72413793 158.62068966 165.51724138
 172.4137931  179.31034483 186.20689655 193.10344828 200.        ]


In [78]:
print((arrayB>=20) & (arrayB<=100))

[False False False  True  True  True  True  True  True  True  True  True
  True  True  True False False False False False False False False False
 False False False False False False]


In [79]:
print((arrayB>=20) | (arrayB<=100))

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]


# **Operaciones especiales lógicas**




In [82]:
print(np.all(arrayB>=30))# Devolver los true si todos los elementos cumples

False


In [83]:
print(np.any(arrayB>=30))# Devolver los true si alguno de los elementos

True


In [88]:
print(np.where(arrayB!=0))#Devuelve los indice o posición de la condición verdadera

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),)


# **Secuencias de Datos**

In [101]:
A=np.linspace(0,100, 40) # (min, max, secuencia)
A

array([  0.        ,   2.56410256,   5.12820513,   7.69230769,
        10.25641026,  12.82051282,  15.38461538,  17.94871795,
        20.51282051,  23.07692308,  25.64102564,  28.20512821,
        30.76923077,  33.33333333,  35.8974359 ,  38.46153846,
        41.02564103,  43.58974359,  46.15384615,  48.71794872,
        51.28205128,  53.84615385,  56.41025641,  58.97435897,
        61.53846154,  64.1025641 ,  66.66666667,  69.23076923,
        71.79487179,  74.35897436,  76.92307692,  79.48717949,
        82.05128205,  84.61538462,  87.17948718,  89.74358974,
        92.30769231,  94.87179487,  97.43589744, 100.        ])

In [105]:
B=np.arange(0, 40,5) #(min, max, pasos)
print(B)

[ 0  5 10 15 20 25 30 35]


In [111]:
arr=np.full((5,3), 1)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [114]:
ran=np.random.rand(4,5) # 4 filas y 5 columnas
print(ran)

[[0.99463616 0.82119101 0.46395817 0.94148449 0.37622924]
 [0.81452826 0.85078562 0.0701249  0.7228105  0.04303246]
 [0.2471261  0.67484036 0.90073874 0.85907002 0.16326711]
 [0.04505009 0.0786156  0.68099406 0.28542981 0.50497445]]


In [119]:
ran1=np.random.randint(10000,size=(4,5))
print(ran1)

[[6061 1906 8826  943 7477]
 [ 927 5304 9679 3606 8323]
 [ 816 8159 3430 9529 1129]
 [3269 6463 6976 4205 7977]]
